### PR TITLE
Issue #821 - Prevent TypeError in resize()

### LINKED ISSUE #821: TypeError calling resize() via fit add-on
I'm not sure how I'm getting into this state as the application is pretty complex but I have a situation where, on resizing the terminal element, in the resize() code that pads out each line in the terminal I'm ending up with lines that are undefined. This causes the code to fail when it queries for the line length:

```
TypeError: Cannot read property 'length' of undefined 
message:"Cannot read property 'length' of undefined"
stack:"TypeError: Cannot read property 'length' of undefined\n    at Terminal.19.Terminal.resize (http://localhost:3000/utc/bower_components/xterm.js/dist/xterm.js:4637:37)\n    at Object.exports.fit (http://localhost:3000/utc/bower_components/xterm.js/dist/addons/fit/fit.js:73:12)\n    at Terminal.Xterm.fit (http://localhost:3000/utc/bower_components/xterm.js/dist/addons/fit/fit.js:82:20)\n    at http://localhost:3000/utc/scripts/utccomponents/utcterminal.js:31:19\n    at m.$emit (http://localhost:3000/utc/bower_components/angular/angular.min.js:151:429)\n    at broadcastLeftRightResize (http://localhost:3000/utc/scripts/framework/stratosresizer/resizer.js:96:28)\n    at HTMLDocument.handleMouseUp (http://localhost:3000/utc/scripts/framework/stratosresizer/resizer.js:133:25)"
```

I'm using an event from the Angular resizer to call fit() but this is not called continuously while the dragging is happening, only once when the resizing is completed.

I can 'fix' it by updating the resize method in xterm.js like this:

```
        ch = [this.defAttr, ' ', 1];
        i = this.lines.length;
        while (i--) {
            ////////////////////////////////////////
            if (this.lines.get(i) === undefined) {
                this.lines.set(i, this.blankLine());
            }
            ////////////////////////////////////////
            while (this.lines.get(i).length < x) {
                this.lines.get(i).push(ch);
            }
        }

```
But my concern is that, if no-one else is having this problem, it may be an indication of a bigger issue somewhere else. 

- Have you seen anything like this before and if so do you have any idea of what might cause it to happen?
- Is this a reasonable way to fix it without causing more problems downstream?

## Details
- Browser and browser version:  Chrome 59.0.3071.115 (Official Build) (64-bit)
- OS version:  Windows 7
- xterm.js version:  2.8.1

### PR DESCRIPTION
**Pull request by jpmasters**
Updated Terminal resize() to fill undefined rows before resizing them.

Closes #821.

### CODE REVIEW

**Comment by parisk** [comment]
@jpmasters can you please revert the changes in all files in `dist/` and squash the commits please?

**Comment by parisk** [comment]
Again, thanks for this PR @jpmasters! I was able to remove the checked out `dist/*` files myself, without bothering you 😄.

**Comment by jpmasters** [comment]
Awesome, thanks @parisk, I wasn't sure whether the /dist files needed to be updated or not. Does this mean that gulp needs to be run after xterm.js is added to a project via a bower install or is this done automatically?

**Comment by parisk** [comment]
@jpmasters the `dist/*` files are updated only on new releases and they are there only for Bower.

This will go away thankfully though on 3.0: #406.

File: src/xterm.js [hunk 1]
```diff
@@ -1941,6 +1941,9 @@ Terminal.prototype.resize = function(x, y) {
     ch = [this.defAttr, ' ', 1]; // does xterm use the default attr?
     i = this.buffer.lines.length;
     while (i--) {
+      if (this.buffer.lines.get(i) === undefined) {
```
Comment (Tyriar) [inline src/xterm.js]: The resize rows section below is meant to handle this row resizing, if this is actually happening we should figure out the root cause. `this.buffer.lines.get(i)` should always return an array when `i < this.buffer.lines.length` which is guaranteed by line 1942.

Comment (jpmasters) [inline src/xterm.js]: Underneath the CircularList is just a straight Javascript array so I'm assuming that somehow 'undefined' got pushed into the array. Could that not give the same symptoms? I'm wondering if perhaps there was some kind of problem parsing the data from the server that resulted in an undefined object getting into the circular list.

Comment (jpmasters) [inline src/xterm.js]: Looking at what is happening in the debugger, we're making a lot of use of the RI escape sequence to implement a 'scrolling' area of the terminal screen. This seems to result in calls to shiftElements that in turn calls set() in the circular buffer code which is bringing undefined data from the unused 1000 circular buffer array entries into the part being used by xterm. 

I think the root cause might be line 2282 in xterm.js (Terminal.prototype.reverseIndex). 
```
    this.buffer.lines.shiftElements(this.buffer.y + this.buffer.ybase, this.rows - 1, 1);
```
When I look at the prototype for shiftElements the parameters are start, **count** and offset so instead of setting count to this.rows - 1 should it not also subtract (this.buffer.y + this.buffer.ybase)? Otherwise when this.set is called in shiftElements (line 174 in CirlculstList.ts), it could be bringing in undefined data from the unused array area in the circular list buffer.

Comment (Tyriar) [inline src/xterm.js]: Nice investigation 😄 could you come up with a script or something that can reproduce the problem and put into https://github.com/sourcelair/xterm.js/issues/824? The best way I've found to do these is to open devtools console in the demo and type `term.write('\x1b[blah...')` containing the escape sequences that cause the issue.
