### PR TITLE
Restore the "paste" terminal event

### LINKED ISSUE #671: paste still doesn't work
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

Browser  chrome
OS  mac
xterm.js latest version

### Steps to reproduce

1.  run demo project use fake terminal without websocket

### PR DESCRIPTION
**Pull request by parisk**
Restores the `paste` terminal event (which is also used in the demo).

Fixes #671.

### CODE REVIEW

File: src/handlers/Clipboard.ts [hunk 1]
```diff
@@ -82,6 +82,8 @@ export function pasteHandler(ev: ClipboardEvent, term: ITerminal) {
     text = prepareTextForTerminal(text, term.browser.isMSWindows);
     term.handler(text);
     term.textarea.value = '';
+    term.emit('paste', text);
```
Comment (Tyriar) [inline src/handlers/Clipboard.ts]: What's listening for this event exactly?

Comment (parisk) [inline src/handlers/Clipboard.ts]: The demo and any app that wants to consume the paste event in a single place, as it can occur both in the hidden textarea and the terminal element, depending on the browser.
