### PR TITLE
If bell() gets called emit bell event and add default bell sound

### LINKED ISSUE #853: bell() function never gets called
It doesn't appear the `bell()` function is ever getting called. I was trying to play with what sound gets played but I couldn't get the function to be called. I made sure to set visualBell and popOnBell to true. Is there a config I am missing?

In Terminal.app if you press the down arrow you get a sound and same goes with Hyper.

## Details
- Browser and browser version: 
- OS version: MacOS Sierra
- xterm.js version: latest

### Steps to reproduce

1. Press the down arrow

```js
Terminal.prototype.bell = function() {
  if (!this.visualBell) return;
  var self = this;
  this.element.style.borderColor = 'white';
  setTimeout(function() {
    self.element.style.borderColor = '';
  }, 10);
  if (this.popOnBell) this.focus();
};
```

### PR DESCRIPTION
**Pull request by npezza93**
Fixes #853 

Emits a bell event so you could hook into it and play a custom sound, or you can just use the default bell sound.

### CODE REVIEW

File: src/utils/Bell.ts [hunk 1]
```diff
@@ -0,0 +1 @@
...nskVWRNF9J0RUHKOnByy9WA8Dv6L4AAARMCQUA4GritfVM2lcZfH3Q3T/vZ47J2YHhcmBazjfdyuV25gLAzrc0cwAAAAAYCh6PdwAAAGyWjFW4yScjaWa2mGcofHxWxewKALglWBpLUvwwk+UOh5eNGyUOs1/EF+pZr+ud5OzoGwYdAABg2p52LiSgAY/ZVlOmilEgHn6G3OcwYjzI7vOj1t6xsx4S3lBY96EUQBF6AIBAmPYH4PoGYCoJAADWe+OZJZi7/x76/yH7Lzf9M5XzRKnFPmveMsilQHwVAAAAAKB3LQD8PCIAAADga0QujBLywzeJ4a6Z/ERVBAUlAEDqvoM7BQBAuAguzFqILtmjH3Kd4wfKobnOhA3z85qWoRPm9hwoOHoDAAlCbwDAA56FHAuXflHo3fe2ttG9XUDeA9YmYCBQ0oPr/1QC8IvuCwAAApbUAQCK22MmE3O78VAbHQT9PIPNoT9zNc3l2Oe7TAVLANBufT8MAQAAAGzT4PS8AQAAoELGHb2uaCwwEv1EWhFriUkbAaAZ27/fVZnTZXbWz3BwWpjUaMZKRj7dZ0J//gUeTdpVEwAAZOFsNxKAjQSgA+ABPoY8Jj5y2wje81jsXc/1TOQWTDYZBmAkNDiqVwuA2NJ9AQAAEBKAt9Vrsfs/2N19MO91S9rd8EHTZHnzC5MYmfQEACy/FBcAAADA5c4gi4z8RANs/m6FNXVo9DV46JG1BBDukqlw/Va5G7QbuGVSI+2aZaoLXJrdVj2zlC9Z5QEAEFz/5QzgVZwAAAAA/oXcxyC6WfTu+09Ve/c766J4VTAGUFmA51+VANKi/QPoPwYgYAkA715OH4S0s5KDHvj99MMq8TPFc3roKZnGOoT1bmIhVgc7XAMBAAAAAMAW1VbQw3gapzOpJd+Kd2fc4iSO62fJv9+movui1wUNPAj059N3OVxzk4gV73PmE8FIA2F5mRq37Evc76vLXfF4rD5UJJAw46hW6LZCb5sNLdx+kzMCAAB+hfy95+965ZCLP7B3/VlTHCvDEKtQhTm4KiCgAEAbrfbWTPssAAAAXpee1tVrozYYn41wD1aeYtkKfswN5/SXPO0JDnhO/4laUortv/s412fybe/nONdncoCHnBVliu0CQGBWlPY/5Kwom2L/kruPM6Q7oz4tvDQy+bZ3HzOi+gNHA4DZEgA=';
```
Comment (Tyriar) [inline src/utils/Bell.ts]: I don't think we can just pull in Chromium's bell as we would need to follow the license. Ideally a public domain sound would be used.

@parisk thoughts?

File: src/xterm.js [hunk 2]
```diff
@@ -340,6 +341,7 @@ Terminal.defaults = {
   cursorStyle: 'block',
   visualBell: false,
   popOnBell: false,
+  playDefaultBell: true,
```
Comment (Tyriar) [inline src/xterm.js]: Are these various settings meant to be mutually exclusive? Does it make sense for `bellStyle` to be an `enum`?

A URL could also be used which points at the sound to play so it's easily customizable?

File: src/xterm.js [hunk 3]
```diff
@@ -28,6 +28,7 @@ import * as Mouse from './utils/Mouse';
 import { CHARSETS } from './Charsets';
 import { getRawByteCoords } from './utils/Mouse';
 import { translateBufferLineToString } from './utils/BufferLine';
+import { Bell } from './utils/Bell';
```
Comment (Tyriar) [inline src/xterm.js]: Ideally `import { BellSound } from './utils/Sounds';

File: src/xterm.js [hunk 4]
```diff
@@ -1863,6 +1865,10 @@ Terminal.prototype.send = function(data) {
  * Note: We could do sweet things with webaudio here
  */
 Terminal.prototype.bell = function() {
+  this.emit('bell');
+  if (this.playDefaultBell) {
+    (new Audio(Bell)).play();
```
Comment (Tyriar) [inline src/xterm.js]: We should preload this like hterm, otherwise the first bell will be delayed.

File: src/xterm.js (hunk 3 above)
Comment (npezza93) [inline src/xterm.js]: Ohhh good idea!

File: src/xterm.js (hunk 2 above)
Comment (npezza93) [inline src/xterm.js]: I refactored it a bit so now you can pass your own sound, false and no sound will be played, or leave it as it is and the default beep will be played. Thoughts?

**Comment by parisk** [comment]
Thanks for this PR @npezza93! Can you please change the base of your PR to the `v3` branch and adjust anything that might need change?

**Comment by Tyriar** [comment]
@parisk my comment got hidden above, but AFAIK the BellSound needs us to declare Chromium's license. We can either do that or find a public domain one.

**Comment by Tyriar** [comment]
I changed the base, I'll fix up the conflicts

**Comment by Tyriar** [comment]
I don't think `popOnBell` does anything really, how about this for the options format?

```ts
enum BellStyle {
  None,
  Sound,
  Visual
}

...

{
bellSound: string,
bellStyle: BellStyle
}
```

**Comment by mofux** [comment]
@Tyriar What if you want visual and acoustic feedback?

**Comment by Tyriar** [comment]
@mofux is that a likely scenario? BellStyle could be a flags enum if we really wanted to support that:

```ts
new Terminal({
  bellStyle: BellStyle.Sound | BellStyle.Visual
});
```

Keeping the number of options down is a good imo.

**Comment by mofux** [comment]
@Tyriar Yes, for example in hyper the block cursor flashes for a short moment and in parallel the bell sound rings. Btw. what would be the visual representation of the bell anyway? I really like the way hyper does it because it is subtle but still very effective because the eyes most likely focus around the cursor anyway.

**Comment by Tyriar** [comment]
Visual right now is a white border, not sure if it even works though. Hasn't been touched since this was forked from term.js

**Comment by npezza93** [comment]
@mofux @Tyriar I like the way Hyper does the visual representation too and I think that would be cool to include in here. But I also agree with @Tyriar about keeping the amount of options limited and could argue that this can be done by the user by listening to the `bell` event. I'm game to implement either option. Thoughts?

@Tyriar Thanks for rebasing this for me! I'll try to get those issues sorted out this evening.

**Comment by mofux** [comment]
@npezza93 @Tyriar Animating the cursor is actually not easy, because the cursor element is replaced every time the screen content is redrawn. Maybe we should move the visual bell to a plugin? Actually, the best solution would be to always re-use the same element for the cursor, so we could animate on it...

File: src/Terminal.ts [hunk 5]
```diff
@@ -1893,15 +1893,16 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
...
-    if (!this.options.visualBell) return;
-    this.element.style.borderColor = 'white';
-    setTimeout(() => {
-      this.element.style.borderColor = '';
-    }, 10);
-    if (this.options.popOnBell) this.focus();
+    if (this.options.bellStyles.indexOf(BellStyles.Visual) > -1) {
+      var cursor = this.element.querySelector('.terminal-cursor') as HTMLElement;
+      cursor.style.backgroundColor = "#fff";
+      setTimeout(function() {
```
Comment (mofux) [inline src/Terminal.ts]: I think you should cancel a previous setTimeout when "bell" is called subsequently, otherwise an already running setTimeout would reset the cursor style while a subsequent timeout is still running.

File: src/Terminal.ts [hunk 6]
```diff
@@ -1893,15 +1893,16 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
    */
   public bell(): void {
     this.emit('bell');
-    if (this.options.bellSound) {
+    if (this.options.bellStyles.indexOf(BellStyles.Sound) > -1) {
```
Comment (mofux) [inline src/Terminal.ts]: It should be safe to use `this.options.bellStyles.includes(BellStyles.Sound)` which reads nicer

File: src/Terminal.ts [hunk 7]
```diff
@@ -1893,15 +1893,16 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
...
     }
-    if (!this.options.visualBell) return;
-    this.element.style.borderColor = 'white';
-    setTimeout(() => {
-      this.element.style.borderColor = '';
-    }, 10);
-    if (this.options.popOnBell) this.focus();
+    if (this.options.bellStyles.indexOf(BellStyles.Visual) > -1) {
+      var cursor = this.element.querySelector('.terminal-cursor') as HTMLElement;
+      cursor.style.backgroundColor = "#fff";
```
Comment (mofux) [inline src/Terminal.ts]: Instead of setting a background color directly, we should set a class on on the terminal element (e.g. `visual-bell-active`). Then we can style it via css `.terminal.visual-bell-active .cursor { background-color: white }`.

File: src/xterm.css [hunk 8]
```diff
@@ -94,20 +94,20 @@
 }
 
 .terminal:not(.focus) .terminal-cursor {
-    outline: 1px solid #fff;
+    outline: 1px solid #e6e6e6;
```
Comment (mofux) [inline src/xterm.css]: I think we should keep pure plain white as the default cursor color 😀

File: src/Terminal.ts (hunk 6 above)
Comment (Tyriar) [inline src/Terminal.ts]: I don't think TypeScript will let you do this

Comment (mofux) [inline src/Terminal.ts]: @Tyriar You are right, sorry, `includes` on an array does not seem to be supported by TypeScript yet.

**Comment by npezza93** [comment]
@Tyriar @mofux This is ready for another review. Looks like there's a buffer test failure but I don't think it was caused by my changes...Let me know what you guys think!

**Comment by mofux** [comment]
@npezza93 I'm not quite happy with the css yet. We have to make sure the visual bell works for all cursor types, at the moment it only looks okay for the block cursor. I'd also like to see a little transition effect when the background color of the cursor changes, which makes it feel more natural.

Here is some css I applied locally to make all the cursor styles work, and to transition the background color:

```css


.terminal.focus.xterm-cursor-style-block.visual-bell-active .terminal-cursor {
  ... replaced your css selector to make it more specific ...
  background-color: #CCC;
}

.terminal.focus.xterm-cursor-style-bar.visual-bell-active .terminal-cursor::before,
.terminal.focus.xterm-cursor-style-underline.visual-bell-active .terminal-cursor::before {
  background-color: transparent;
}

.terminal.focus.xterm-cursor-style-bar:not(.xterm-cursor-blink-on) .terminal-cursor::before,
.terminal.focus.xterm-cursor-style-underline:not(.xterm-cursor-blink-on) .terminal-cursor::before {
    ... other rules that already exist ...
    transition: background-color 150ms ease;
}

.terminal .terminal-cursor {
    ... other rules that already exist ...
    transition: background-color 150ms ease;
}
```

Here's a demo how it looks like:
kapture 2017-08-14 at 23 28 40

**Comment by npezza93** [comment]
Ahh good point @mofux. Thanks for pointing that out, I have updated the styling.

File: demo/main.js [hunk 9]
```diff
@@ -70,7 +70,8 @@ function createTerminal() {
   term = new Terminal({
     cursorBlink: optionElements.cursorBlink.checked,
     scrollback: parseInt(optionElements.scrollback.value, 10),
-    tabStopWidth: parseInt(optionElements.tabstopwidth.value, 10)
+    tabStopWidth: parseInt(optionElements.tabstopwidth.value, 10),
+    bellStyles: [1, 2]
```
Comment (Tyriar) [inline demo/main.js]: We need some way of exporting BellStyle here so we don't just pass in numbers. Maybe export it on Terminal as well as exporting from the Terminal.ts file itself?

What I mean is supporting this for web:

```ts
new Terminal({
  bellStyle: Terminal.BellStyle.Sound
});
```

And this for Electron:

```ts
import { Terminal, BellStyle } from 'xterm';

new Terminal({
  bellStyle: BellStyle.Sound
});
```

Thoughts @parisk?

Comment (parisk) [inline demo/main.js]: What about just using strings? For example:

```javascript
// No bell
new Terminal({
  bellStyle: null
});

// Visual
new Terminal({
  bellStyle: 'visual'
});

// Audio
new Terminal({
  bellStyle: 'audio'
});

// Visual and Audio
new Terminal({
  bellStyle: 'both' // or ['audio', 'visual']
});
```

**Comment by parisk** [comment]
In response to https://github.com/sourcelair/xterm.js/pull/878#issuecomment-321617589: I would prefer if we went with a public domain one ([example](https://freesound.org/people/zgump/sounds/83540/)).

File: demo/main.js (hunk 9 above)
Comment (Tyriar) [inline demo/main.js]: That's another option, I believe we can extend the StringOption type checking later to include values as well which is probably the best of both worlds (standard JS practice, strong typings in TS).

https://github.com/sourcelair/xterm.js/blob/39328d6e0c05b1f1f574303ad0288687ca6f813f/src/Types.ts#L33-L35

We can follow that up in https://github.com/sourcelair/xterm.js/issues/889

**Comment by npezza93** [comment]
@Tyriar and @parisk, I have made the requested changes, let me know what you think! Also, want me to rebase to get rid of the conflicts?

**Comment by mofux** [comment]
@npezza93 👍 rebase please 😅 That should make looking through the changes a lot easier.

**Comment by npezza93** [comment]
@mofux Rebased and tidied up!

**Comment by mofux** [comment]
Just tested your PR. Looks really good, well done! One last thing I would find useful is if we could add a dropdown to the demo that lets you choose the bell style.

**Comment by AndrienkoAleksandr** [comment]
@mofux +1 dropdown

File: src/InputHandler.ts [hunk 10]
```diff
@@ -7,6 +7,7 @@ import { C0 } from './EscapeSequences';
 import { DEFAULT_CHARSET } from './Charsets';
 import { CharData } from './Types';
 import { CHAR_DATA_CHAR_INDEX, CHAR_DATA_WIDTH_INDEX } from './Buffer';
+import { BellSound } from './utils/Sounds';
```
Comment (Tyriar) [inline src/InputHandler.ts]: This can be removed now

File: src/Terminal.ts [hunk 11]
```diff
@@ -2271,6 +2282,27 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
...
+    return styles.indexOf('visual') > -1 || styles.indexOf('both') > -1;
+  }
+
+  private soundBell(): boolean {
+    let styles = [].concat.apply([], [this.options.bellStyle]);
+
+    return styles.indexOf('sound') > -1 || styles.indexOf('both') > -1;
+  }
+
+  private preloadBellSound(): void {
```
Comment (Tyriar) [inline src/Terminal.ts]: Let's remove it too if sound is now disabled

File: src/Terminal.ts [hunk 12]
```diff
@@ -147,8 +148,8 @@ const DEFAULT_OPTIONS: ITerminalOptions = {
   geometry: [80, 24],
   cursorBlink: false,
   cursorStyle: 'block',
-  visualBell: false,
-  popOnBell: false,
+  bellSound: BellSound,
```
Comment (Tyriar) [inline src/Terminal.ts]: It would be cool if this gets lazy loaded using dynamic imports https://github.com/Microsoft/TypeScript/issues/12364. I'm not sure how well this works on the web yet, I guess we can defer this unless you want to have a look? https://github.com/sourcelair/xterm.js/issues/894

File: src/Interfaces.ts [hunk 13]
```diff
@@ -113,6 +114,8 @@ export interface IInputHandlingTerminal extends IEventEmitter {
 }
 
 export interface ITerminalOptions {
+  bellSound?: string;
+  bellStyle?: string[];
```
Comment (Tyriar) [inline src/Interfaces.ts]: I think we decided `bellStyle` should be a string: `'none', 'visual', 'sound', 'both'`?

Comment (npezza93) [inline src/Interfaces.ts]: I took @parisk's comment which showed the ability to pass a string or an array of strings.   https://github.com/sourcelair/xterm.js/pull/878#discussion_r133476748

It would simplify the code if it just expected a string instead of a string or an array of strings. Which way would you like to go?

File: src/Terminal.ts (hunk 12 above)
Comment (npezza93) [inline src/Terminal.ts]: I took a stab at this but was getting some errors so I think I'll punt this to a different PR if that's alright.

File: src/Interfaces.ts (hunk 13 above)
Comment (Tyriar) [inline src/Interfaces.ts]: Oh I didn't realize - I think just a string would be best for simplicity :smiley:

File: src/Terminal.ts (hunk 12 above)
Comment (Tyriar) [inline src/Terminal.ts]: I thought it might not be so easy :+1:

File: src/Interfaces.ts (hunk 13 above)
Comment (npezza93) [inline src/Interfaces.ts]: Should be good now

**Comment by mofux** [comment]
@npezza93 Last chance for you to change the default bell sound to the one you love most, because it will be heard by millions of people soon 😅

**Comment by Tyriar** [comment]
We should vote on some candidates :smile:

**Comment by npezza93** [comment]
I like @Tyriar's suggestion. I'm not a huge fan of the one I picked.....haha

**Comment by Tyriar** [comment]
Here are some decent candidates from the first page of https://freesound.org/search/?q=bell&f=duration%3A%5B0+TO+1%5D&s=score+desc&advanced=1&g=1

1. https://freesound.org/people/HerbertBoland/sounds/30161/
2. https://freesound.org/people/KeyKrusher/sounds/173000/
3. https://freesound.org/people/FairhavenCollection/sounds/350548/
4. https://freesound.org/people/sqeeeek/sounds/237105/
5. https://freesound.org/people/sqeeeek/sounds/237106/
6. https://freesound.org/people/CJ4096/sounds/66717/

Gotta go btu we should check the rest. We want a very fast/small sound.

**Comment by mofux** [comment]
Here are some to choose, I like 1&2 the most:
1. https://freesound.org/people/uEffects/sounds/180971/
2. https://freesound.org/people/joseph.larralde/sounds/352501/
3. https://freesound.org/people/rwm28/sounds/48190/
4. https://freesound.org/people/marcolo91/sounds/156064/

**Comment by npezza93** [comment]
I'm a fan of @Tyriar's first one:
https://freesound.org/people/HerbertBoland/sounds/30161/

**Comment by mofux** [comment]
Like it, but it's quite long imo. 
`1.4` seconds vs `0.2` for https://freesound.org/people/joseph.larralde/sounds/352501/ for example. 

Try to search for `key` - that also gives nice short results:
https://freesound.org/search/?q=key&f=duration%3A%5B0+TO+1%5D&s=score+desc&advanced=1&g=1

**Comment by mofux** [comment]
I've just fallen in love with this one: https://freesound.org/people/jonnay/sounds/3168/ and its muted version https://freesound.org/people/altemark/sounds/45759/.

Looks at the wave! And it's only `0.001s` long!

**Comment by npezza93** [comment]
What if I could trim the audio? 😄 
(The audio is in the zip. I also added the uri here just in case)

[bell.zip](https://github.com/sourcelair/xterm.js/files/1232998/bell.zip)


```data:audio/wav;base64,UklGRkhoAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAARkxMUswPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkYXRhUFgAAAAAAAAAAAIAAQABAP3//f/9/wAAAQACAAYABQAAAPz/+//6//v/AAAHAAkACAAAAPv/+P/1//r//v8JAAwACgADAP3/9f/w//b//v8KABAADQAFAP7/8v/r//L//v8KABEAEQAKAP7/7//o/+3//f8KABEAGQAOAP7/7P/m/+r/9/8GABcAHAATAPz/7P/n/+T/8f8FABsAHwAWAAEA7f/j/97/6/8GABwAIQAYAAgA8f/e/9n/5/8EAB0AIgAeAA8A8f/Z/9X/5f8BABkAJwAlABcA8v/U/9L/5P/4/xcAKwAuABkA9f/T/9D/2//y/xMAMgA0ABkA+f/Y/8v/0f/r/xMANwA4AB0A///f/8X/xf/m/xEANQA6ACUACADi/7z/vv/i/w4ALgA+ADMADwDg/7j/uf/e/wUAKwC0AKMANQCs/0n/Pv+J//X/ZQDGAL4AQACy/1f/NP9g/9n/agDSAM4AVQDI/2X/Iv84/8j/bgDRANUAdgDr/2v/DP8c/7X/ZgDIAN4AogANAGT/+/4O/53/TAC8APEAzwAmAF//9P4E/3b/IwC7AA8B7wA9AGj///73/kj/+P/BACoB/gBZAIr/Bf/g/hv/2f/EADgBCQF/ALv/CP++/vj+w/+5ADQBHgGuAOz/Cf+a/uH+p/+QACsBQAHkAA4AC/+I/s/+gf9eACMBcAEPASgAH/+M/rT+Tv8oACIBmAExAUEARv+d/or+E/8HACEBrQFPAWsAd/+o/lr+2/7s/wsBqAFuAacArP+r/i/+rv7R/+QAlgGfAe8Azv+w/hr+i/6f/7MAigHUATIB7/+4/h3+YP5X/34AgwH9AWgBEQDd/i7+Mv4C/1EAhAESApABTgAO/zv+/f23/igAfAENAroBmwBH/zX+0f12/vn/XAEGAuQB+QB+/zH+tv1K/rj/JQEAAh8CTwGy/zn+sf0q/l//5AAIAloCkgHt/1z+sP31/f3+owAQAn8CvgE2AJn+tP21/ab+ZQAHApEC7QGPAOb+p/11/WL+KADeAZUCJQLxADP/ov0//S3+3v+aAZkCcQJNAXL/tP0k/ff9hf9EAZwCwgKdAbL/3v0f/bf9If/6AJsCBgPgAfz/K/4j/V/9v/66AIoCIQMkAl8Ajf44/Rr9cP5+AFMCHgNpAsoA4/5K/er8Kv42AAUCAwO3AjIBKP9n/dj85/3Y/6wB6wL/Ao4BZP+Y/eD8m/1j/1oB1gIxA98Brv/e/fX8Uf3s/hIBwgI/AyQCFQAu/gn9Cv2G/s0AmAI0A20CjQB//hL92Pwu/ngAWgIiA7MCCgHI/iH9wfzl/QgACwIUA/UCcwEV/z/9w/yf/Y7/sgEUAycDzQFy/3v9yvxf/RD/XQEIA0gDEQLh/9H90vwa/aX+AwHpAlIDTgJbACv+zPzd/E/+pQCrAlMDngL0ACb+IPzi/J79ZgEG/pwFCxv/BcX/EPt61tnxpuUwFt5U1ukX8ckclPUdyR/t4xT5Bfoazwld7k812vNkre0F/xR6+7b/YSbUDv3/rABUuhgFEiVj04QGXD2nDf7tNfOB7l3pxg4p6hH1hFqE/zXaTA8b+RHhDucWC8kIgC74EojPgRocDye6SPIdF1IOxBCuD6EFAPvNDnC7seDAPZ7xofvaJCMW2vkH63ThfeOOIJsFGN80RDsiNNBB+uPwW/Ji9xACfAEIKJM0QMQI9SMcJM806mkQmRI7HiwSZO+h79cYV9ajwZ443RLa/cYazP9KAdryF+Lh0xEj+CZT2lQjYSyh4Bvs6ea96/QQ9Qw2+TcSBkIY2rrNMRhd4uL10wpKCich0B8q7EzQthde+HLBwx1EJmoFeBxF72Dw8QHV7Y3OUQxgR2fpLQdpIdfnoPOp5IHfWhPWKdz5pPjPNyn48L+OBMHtWv+KHSX6+hV/JY78UrzI/hsVgtPFD3ggkgvNIJrx6tNiAVIFLdkb9ThH9Aku9TkVe92L+5X1vNddBuk4oRLM4fwf+QWwy2H2sO9A/gwzYAF7+PcgwgulxA/eTB4p7P0QKxyc/HQkXv7bx9vp3BnM8P3rJTQgG+f4egpa1DbthRPm30X2MDJPKxLjjwDTBhzVHf7v7nz1DDmlGxrlJQfOFNHWkNSDEEcAWxWQJh7p7BPFEU7MStVrFZoQi+/MJKgUbf04DR/TQ9Y/HhsAJeqfI0MvrvQY7fj7H9e4ByECKuU7Md4ufuxu6I4MWuiz3TkIZADYGyowL+kc8eUYj9/E0DoGDB7RBLYaFwvb71kUat7PyHcSNh7t9aIPiSa/++bwN+5M1U4GSx+x57cVaDZD+b/dzvd48WjqfxHB+1sRJDlH9o7WPQgS+ffWOgGeGNMRHR7nBgDd1Anq+hjG9wGcKY4L7QUSGFD1Y/R19q3PuPxUMLkAg/qJK8kDjt/R7VLr6vO/HVQHn/omNLcJ2c5P8IEC9+ehA3AWuwh9JWIMGNLa8U0OzdlK8voopBQ7DK4NyOnx7BoH/tcP7HIyXhkc9uITFgbF4N70OOY275so5BiH8MgaThi+1Nrifv0G9NYNNRzj+9waShrP0TDdHQwY9kzwgiKAFGQM5xKw3ojebg1N8d7iwCacJzL96wSd/Mbe6/vT86riGyhnKvP0MQCzEwXj1d50/Qjy5xUvKZr3OQNxHhXgHNGOAnIFBf22HdgRTf/AGlPjKM1CCaYHlu3WFPcpjwHjASX2eNVe/YMJ8uKBFws1Mv9o87QBSuvG49EDOu/hCutKtwt4yP//Vgqy1KvqQBXIH+EfEQhM3e0JUgsCv/zjMSoqGoYBLRU2CHD+DPIbx4npEDPGDMrr3yZmHxbuJ91C45TzaRfSBTHyxTXyJHPVX91VBNrzFvMYBL8PUi8RGW3ViuYAFY/ipt3LE4MkgRgGBnHxXPX6CSLWO9fyJgsrJP7SA3sNffrq7PfX0ekZIUEgBfByFDInx+sa14flgAAYDgoMMv2nHucpRODK0Hr/Uv4Y8TsHLRakJgISHeJS3ocKnvf61VwSqyr8GAkD/u//8mn9X+Yn2lMb/zJ0AcP7VRGo98Dpn9wW65YfZiLX/GgBpSZ78tfPLexe/L4O2A9tA9sWFyX356vJMvpRC2Lv8weIG0QaQRjZ4vzZ2ABrAbndVAeFN+kRvv6r9UnrYPql8Rvb/xKBObkJefBHDoD8RdsW7enrBxURLUAAqvkwHmwA7MT/6bIJywV/FZgOKgWdIDX2GsLc8j4UF/Z1+9kqqxSBCJz2vc6w9/MO1+dM+JI6RB3p7bn6h/Gq5i79Kuyi/c0/VhUm5asDQwt81iji2gXHA/sp9BbL650NbA83yFbZPxniC+YE/RzHCUQDZwrZx2fbwCCgBcnw5SNWKK/xmfb25GvezRDfAXvq3y4jMxnl2+lZARHnHOs5CXn6dCWEMgPi+OwVEyblrM64DpAXVA5qIgj7dO5nE4niUMLZFl0juvsfEX4eb/Wh9qrsJsqiEdwjRu4TDoI2aPnX2kX27+Vu95MYpvp5C7U/r/aczsQCFPpV3kQDWRm6C18sXAFe0TYHPAHHygb7XjDcDO8M0hAQ7Iv0D/+wytX2vTuTBvP5kh/hBnDdyPDY5CzxYS08ChP0Wiw5E67KI+lv//Dv6wpJF40CDSOcGPrF9ujdD4TndvCrJO8ZYwxAEZ3dAubiDYPjaOHsMSgly/gECr/9YOUZ9MXt/eODLVEo1Ox5DKcWP+CH2nT6/vVmFoAi6vjDC94hN9rvzCgJOADS/EwYvBV/CtgUGOLMzPwNOQJm518Xxi1kBsT/1vGD3fD8qv5x5FYXbTt//LnzJAVy7d7kVfWr9uASejSi/Z3x8RSw8s/OX/SDCsULEh6PCjv+vhHP84HE0vg/F239Og0HHDUOGQF28DzRpPe+FA7zaAWpLx4TFO+58QnnqfJBAe/2LQj2NHQSSOO+/MH3KOX27t0CLhLcJ9sOLeqeBIv/JNV75qkT8hKJFfgN/v4UBTn3kNLC5usd9Qr2AxAZqRER/d3q4tsn72gVpQJ3/lklSB2L7F3oN+2/8awCzfytCQAp6hsG5PfstP/d6K7utwMPFtgiwBHN6gv45wLf3tHgwxKnHCQQDg97+0AAYfim2GXj0hlrGvD9ThSuEsL5neqc3ons2hXrDcv6PR0VIYjuSt7K8iXxwAObBswD1SSvHrfn+t5nA+Tw5empCWkWaB32FWXrVOquBxDoYdwGEEknPgsjC3UBG/IG/UfhuN1jFrknLf1HB5Qap/WE5BjopOpAD0Ie6/hADy4n5/Jg0jj0AP1F+IYRXAjYFGAk6O4H0dn/8ALV4pUGBSOPFKUPofht3M0Avvxd19sGfDPaDwr5zAod8n/tavNb3yMIXDReBwjy1hunAUjWYekZ+usBriH2Cp/4OiQ0A17IwOhxEHn4kgSMGygLSRYKASbM/ewUF1/rz/N+LIUdVPwT/XznVenYCsLnsPHcNsIhQOmb/kAGQeFe7jv2lPvmK6UfyuWVB3oWDtY12EQJAAvtDfobAPujCM4UydBN0gkYew4n8koaThyqAWz/rd+f2PAUIAkM5NggFDLH9krp/vgm6KL5eAME7hYibTZH7RHjERAY8FTabf9KCzYXFibR9mLpFRkP7XLGEwSUIqgGrA1fEGv5eAeb6nrI6gcjKYv0lgK+KiMG8Onl6mTiP/4VHOXxfwTGOvMFU9So88/9JuzUAbcEMA/rMBUEK9GIABYKdNbQ8IsdahlxE30GqecvAGkEysuS7h0w5RX6+JoQxAYt8zfvV9mu9LEsRg3q7RAiAhmb39feofNu/LIQ1wkH++coUxpP0cXeyAug973x9Q7NFpMehgsg2vPn9BLJ6VDfiR5EKccJsvxw9TTzrv/o4dHiwCjIKkr0I/7DEn3z4uL25PL49x+cHNzxPwqtI+jmzM+M9aEK9AikCkMGohflGvrdmM+BB7QL9eyXB2QhuhpvAtnh1uP4BwD+f97nEcA09Ay17zb11PiK9nrqF+mPHbUxpv0/7SMQ/P0g3JLkaQBQH2waJvt5/tEcS/QIydzvaBTVDYIEtQnXFC4UOeQizsP+rBbP9Nv8xSRAHPL9gd/Z5KAELwOD51oHWjdJE1voae+b/Jr2Y+yB7TIaNzO/ArPmpgbuBiHbduLZBO0fGR0B+xL6oxUD/F7Ioul8G/wSDwJVCR0S5w8n6ZzKT/s1Hej8tfXWI0Qg0PZu4R7iFAMtCo3t7v8/N6caIuB96lAAQPYe7tn08hJnNXYJ2N02/+gNJ95q2yUOLB86G8kAxPI7DZgEIcvm3jwkNxqu+x8JJhRrBYru58547wQmbwez7ckdeCp/7k7cbOog/BINM/p2+IkuqCgT2p/d3wj++YnnsP6HFC0pTRbW2ujuRhUo6ZjPGhFHLIAP2QJB98X+7AWq2rXRmSJpLTz0B/9FHT8B2uOL3jDp8B4GG1vr6wwnNFj0Icnv8okDxAJ7BPv/6huBLi7m+sfLCQkLAuAG+gYlDx5lEN/pud6DDp/9yMwoAow/YhDP8S4BqP2B93Hp2df7DiM+4P266VceOQ5P1HneQfrdD8ggLPuJ+qAsdggAvQfmCBkwAGv7Fw9sF48d4vgfwwr2xx6h6IPo0SxRKon77+/75VP7Vwfo3a3vnD9eJsPfXfjvDPLuYOJF7BUGDjWQFZXeLgxHHqHXIsuUCYAXLhEuCYf8QBdlEjvJZs7EIJoTBe08DXYlzg4B9O/U4ONgHTsAW9+VHxU9EfhI3dr0sPiQ/ALwmPFjLD43AeXo33QUV/q41AbweRWYJCcbk+oJ9oMdLeqDv1MBmS3VClkAIwlNDvIG5dqRydQR8ylj74788ywnFZTitdvq6v4NXQ5H6b0N9T4hB4zLCPCIBwP1Uu+o/wcjvDBh9qXR3QghCyfV4ORFIRAp6A319DPyEg9+9gvGsfGJNvoXHPKlCDEU+PzI2kfVdQWpLfr/vu/5Ja4fut6u0Bn2rQwoCyj2kQgGNCsSNMvJ3+YQ9/tV6R4DLihUJ/T5cdXS+LcR49+h3UsfJzQVCTrvi/ZyB3j2HdAq7bUxQyaV7n7+oxdr/U/W1NiECLUo6gqa7nEagiOp4snIvvV4FLoJW/lZCY8tUxJl0PXVARDUBuznKgKGKYUnTfbO1ufyhxBS6vLbpBsNOQULzOhd9SkFm/ee1PPsLC8+LEbxE/Q8GOv9Ida12QgJNypVDzXvDxGvJL/lnMSH9MoZ4wqC/PcHNSfgFDfRndCfDcoQzeerANQreyMp913W3+w9EIz0YdqgF4Y+kQui4nj1uwKq9VreAOrTK5IzfvOb6X8XigKh0GDeJgvyJtoVJfKVBBslWO2Dva/yWCLECgL7Iw40HVcT0Nl2yPII7RzZ6tD3ajKEIp/vjdsb6poIYgH/3kALB0WQEdDX2/KCCVDuX+Mj80UgmTd3/TjdqQ8HD9XM4tiIFqckuRGH/KL81Rjm+0284OYhLa8Sh/DhEX8gIQX04fHMzvoSJUT5j+qkL1kuBuXL1uXzGgFhAJ3wigD4PJYhdtFm5AEUEvIW2d7/HyFEK+EJuN0J/P0XeNj9yRgbHDFGBxP8bgVjCM3848xv2MAq1yV36poFqCz3/3bXD9ua9qkbVQy06lIcbDrJ6afFafmXCiv14vhOCvQpdyc83WvRqBGNBPPQ2vqVMJQiggPu6l/waw2/7YnGTQ2OQTsKg+w+DPQKa+0b2hneERo8Min2A/ItLE0Nvski2iAEGBIMDT/7oQyTMgr8oLu+7dQaLfdU7mUXXSdaGT3riM8LABMTg9t36gc3dixg9cvrKviN/ubyDdd+/ZFBShtg4XQBbxds6CPTfO3FFAorGgfg7FQamBrozLnLNw0iGjwDNwJAEX4gnwPCxArdBx6GB7vlHBOHMoQPIecJ2uX1UA+z7tHk8isIOvfzD98X/rIAMerB45v/XzSRJs3lj/AYGRzzC8pd7ycelCPbCPv02AuVF3HbTsM7CLsmogPR+nwXBhx3++vPUNmAFdEUs+rQBv81oxP53Y7bZPnoCOL1Ue0PH947QvyE1dH4PAjU6UbiyAe2Lo0k9u2Z6HYQJv0czC7p5SNUJgEFZvb1CdIOWuOexrn/qCx7Cgf2XBNyHjD3vdDK3HsQpxhW820AojD/GEPb2dew+gwLK/eO8rcbZDb6Ag3SOvK7CtHuQOKaCA8voCIm8JnltAnFAFjSS+VeJREpDgWf9MkFwAxX5VjL/PrqLqwQdvOaD3gcq/YF0nfdQA72HIP4Lv3XKgQcCNoZ1Vb8FwoN/RH10xfmMgMHTtBT66wO7fFb4wQL1CxMIIr0y+BhA5gF7tct4tUl5y1zAFv2bwKdBh3r4M8B9o4viRnH7roKMh5h8x/SXOMHCaMelwJu95sj4x+W22PNsQEDDPH61P3/E6IqnAyl0i3gGhLP+o3fEwwIMaIYGvZV5dD2wAgX4wzeCiEsN0f+TO53CDsAFOmW2w/zTChbJaTvmf15ISz36Mpf6J0OcxVKDBT7jBS0IXHkHMU//goZVvYX/dAb9x8cCSfeoNe/CokKMOAVA5A35Bm06h7tePXd/fzxR+KrFN07ngeH4KMGpQhI4OTfhP0pHTwmIv1z7x4ahQOOyNvgrhonFVEECghGDMcVT/GYxvbwEiM+AOzwhx/gIwn8+eK835z7zBHz7s72sTPXJG7jX+S9AaT2LPDb8lwM5zJnFZfdgvbfEt7k2NbRBmwhSRn3Bi7y3gZLCyvTLda2GmMjRfsFBX0VgAfg8OHUXOffHWoS7uyQE60sefpU2DHq6PtPBy8AX/f+I9Yr9Okp1tgCLQLP5sH45BTmJOYW2uhS58kO0PTD0lUBfSyOFtr9Zv0G/vgBv+Ok1RgQhy3yAev2pxiwCr7l09wX7qkRYBov+EEEPyqtA53RWeWRB50CF//XBDwYTCVt9dvRsPdhDcHrB/FgHNkkbgxM8OPngQBo/4jbB/iwLdwe+/Vx+aEEh/eR5xXhVAcMLMgNNvEwDn8RwOQ42G/2lxGRFN4DkwBpHaAKntTB3Y8JnAva+fYHlRq3Gf/4N9ch7vENwPcJ7oEYNik/CWTr9uwD+zv93Ojh9B8oCySY98vwjgQ++g/kl+igCOclgBPS80UDrhAg6rrWB/ZfFuYT1QN2BAwTowk1247adwdNEd/9CAT5GokW9fVW2+TrkQppABvxgBOvKKIJpekM6j386vsV71P4tSEeJhf5/uw7AN779ea16hsKHiR4FC32tvyzDMbuU9dq900WTBZDBXMCoQ4sBuHgV9n2BZ0VTgA5BAgYehIt9jPd2embCT0GS/VeDrkoCQj/5xbra/ge/u70tfpXHKImy/sS57b+/Pxm50DwCwupH7IXnfco9koIx/TS14j2hBs/E28HtwPLBlcDMee/2UgBRhyeA9H/FBn5DkTx0uNu6CkFqQ3u+rUH8iWRDAvhrOt6+3v5sPvFAL8U+SOWApPhvveqA2bo3+4ME9oauhM0/ynwvv9W+wHeq+8gIEsY2v9HB0YFZ/mA7aTgO/l2HgMO2fkaE2cUwep24uXxHf6YDrEG9QIMHCgTwOGe4eEC+fsn9+4KwBN6GGcJduSK6yEGefN36Y8T2SJ6CW4A6/Vz8677KusA7NgZxiPO/cr91Au+9Jfn0u2m9zsWjxmz/JIF0BVM8VTY6PZhBXsFsg4MCfsN7BEn7BbZDf4fCdX0cQeLHXsPPQPa717k/v2RAB3uDglYKekM+vPt+7Pz8fA19pTzKQ7YJtUHSvKwBrr9WOBy7usD7QxpGYII8fuxC377xdhY7WcQgQc8B98SBgoIBYj1Udwr8oQPGgC5/kQdKhbt9s3xrOta8kgEt/tRAnsiWhdZ7z3ybfyz7YnydQGjCgoeUBK/8RD5sgHm5yrm/AlRE1IPAw+9/ov9IP1N40nmHg7yE1cDHg7hENT7wfHL5wrsJwuzDEwAlRJRGtv4dOdB8oDzmP3SBgYGIheOGcH1Kuiz+aj21e4zAwoTsBRGEhD5Ze85/JvxCuixA2Ebvw9sCFcEIvih9eHsuOjUBrwZIQp0BmsOMv896kzrb/HpA2ESvweYC5YUi/7Y5LbsLvrw/BMH6Q1sEb8T+Pvc5Wjyh/pt9RIAahWsFmkLG/3D7Wb0NPbN7uoAxxmsFakFUAA9+czwgO7c77UC0hlsEAAFtweW/mHsJOiK9TUEuBGPDssIGw43/yjnaemO+QUCfQjzDokR2Q2P/R7nxOzU+0T6UgPgEusWLwux+gPuiO/d9wn1rACJGBkXgwaC/SX1tPD6723z6QIDGM0VYwOFAz38QOz46uL0TQVLEy8SYwfPB93/OuiD55f6FwMNDG8RrQ0fC539s+i+5738RwAfA84UjRQ4Cdv7HexL63X59vvz/0wWpBqqBNr61fTv63LzWPhrAXEWcRo5BBT7Z/0i7MzpmflnBLQSpRe1Bpn/9P9n7FDjhPpMCQkKrRQjDhgD4P7l64Hj1vnKCfcDiBCNGEIF9Piz77zmFvdwBZgB7g+jHT4IV/IV9eLtte5JAKIDhRCGHVsJUvJ++AL0lub8+HQLKQ/RF7AM7/bG+lL09+Lw87MQ0g6jDQITBAB596HyuuOo8v8P6AwCCFYXAAsu8bruAexo8KsJJAtHCEAaFRCs7jvrz/UD75P8YA0tDVsY8BA08MnsAvp27RTxPQ8rFlAQJg9D+f/uivi96sLsyA/dGqAJiQtiBwHxZe9j7AruLQ0gGbIGSwwgEYbzVeR68DD1DQNEFEoKWg90FLfzYODj8yz7bPeeDLsV8RCnD9b2V+Pt9fr5fe8lCH4fRBIHBX/+5Oy58Cv1e+0ZCE4iixB5/1UGR/i+5gfuM/W2BvgcGw+FAXgNlPx63xXpf/8lBEsPVRPrCTQOsPuM3ZfqpwPB/nQDdRnwFbAGuPiu5X3sQgC/9/3/YR+vGxz/s/Zk9DTsufPL9ikDliDHGbn7mvvO/l3p+OXe+igLkRdBFRQB6wKnAWDj6eBCAAoP3wrbELkPrAZU+1PiweNWA7IJWgHIEnockwZ38DbpRuyQ/A4BMf9RGTQhkgEE7U7zVPPk7gb55wfeG6Ach/6U8ij93fA14yv3khLSGNkQoATJ/YL+rOkg3sr8qRWTD7QJ+Q8aCdT13+OG5CsA1A8pBWMMIBzJCojsN+T78M38xgHOA8UUkCHbBJboHu6u96byrfWZCt4dkxrX/y/vv/i29fnkSvT9EwseMw+QAJ3+nPui61LfBvpCGb8Tmgd2C2EKXPb94BjlaAEKEtsI0QgDGuoMQOso4RPwqQEDA+MDSBRVIAUHQOWX6sH52PV19pIJ7x4+HPb9LOxb9rD4eefL8VIW4x/BDwn+0/p9/P3sxd9A+JAc0BdjBCUJCAqX9d7hnuOWAZ8W8gqdBRYXPhDY6BbeH/IoAqwG8QQhEdkffwlq4mPlrf1X+Z70sAvJHu8a6v/z573yi/xY6wPuEReDJfgLffw8+gf5CPBY4r70+x1KHiEBGANkDdj0yd6L5zIAsRepED8CaBGyE8bqotas9G0HNATxByIRihpZDKLjC97i/sgB8PGsCL0knRdP/YvqD+0O/f3yBuxQErgsAA2Y85X8+fkp7OjnTfWiGcgkGAOD+UENi/vn2LnmYAdPFKMStgV4CYgSn/G/0Z7vYBGHBRoCChaXGCAHCekL24z5ngrv9TYARyd2HZP0YOqC8Lj3AvhZ8RkLvi3rFNHrOfY3ApnqauTw/BYXriIfCsXznwU9Azzb/N2BDVMa3AucCLwJkQpZ9j/VMucKFaUPWfsIErwfhgHm5f7gZvSTC5b/lPu6ILYlsPMG4DH2ivp58zf4XwvmJhYbwewj6+EETvPl3RP9Ex/6HCsKIvfk/GsDHuQJ2XUJKiXsCoQAgA6GCEjxOdyH5Y0QBBlC/a4HJCLSBhPdOuLl+TUHYAR+/ywYLSZh+gnY6fF1BK/yr/TlEW8jxRc48mflof9K/FPgbPWNJFMhOgJ2+B39yf3J6ZXcvgLpKCkSmvgUCq8Oju122pPrTQ1vGpoDkQFkHGUNe9yu2u7/2Ar3AFgDlBZzIOH+7tds6rgITfrH76wQeyjbEjbx8eZr+i7/Jueg8YshRyhHADDx3P/o/VjosOGGAdEm/hc79xcCKBA88vHVpuzMEZ8Y/gXtADoWfA6C4EvWnP5ZElwB3v8FGA0eXP1B2s7mnwj3AN3wkwvjKSQVGuxj5sb6WP+36wHyKB5NKnMCrOuy/NcBWelg4aQD4iWmGX/3qvx+DsH1KdfA6b0UvRunBIj/EhPlDeLiS9U4/RIW8QSu/aYU0B7C/GPZ+OXfCPYF9/EwCVsoUhZ667Di8fpLAp7u8fFGHHErHAMj6GX6pALY7IPiXAIgJw8b2faR97sNtPhz1zHqQRXiHfwFkvwcD5wOUOXD0238oxp+BjL8FBPoGw3+ytmn41UJiQtl87MEBilzFivpMOL++ZMDy/P18XAY7iweBevi3fdkBgPt1eR2A88kAB3A99fxqwqV/rzXxOc1GeselQQD/Z0KOwxn6onT1fhJH1ILxfbLEZUcgPr52x7k2gYgEH74rv4QJiAbtuVs3sD9vwM+9Z323RNrKrEJGuC+8EcLtfEh4ckGhSV+GQL66e/6A+MC3N114tIZkyXEAIP5bQyMB9LrDNnI9C8fVhNq9G4JrSB6+mLXe+hrB+EO4/6T/Yodrx7E6JXWvv4vC6jyA/iJFs4j5gom44XpJArV+6/fLwLQK6sXSvV28mIAUwCw5mfiyBPxK74DHfBIDPMKCudZ3dT3lhrNF6n4EgDMHRwC7NK95cwOMA4Z/h0CKheQGrPvndOZ+GoTXPdq8YoZRiSgBFvmBuluBFcCeeaU+vYrFR6l7s7ugwQb/avoXumNDt0q6wo668ADFhG06MHY6f1UG+IUX/1j/QoVAAcu137ezhHpFef5OAEUGbATFvHV17bykRQrAZTuSBOiKSUCVeGz7PECywGe7nb5DSU6I9DvuOWTBVwCxuUK7SoRtiXSDc7sIPv3DwPxC9bQ+zEigxP3+hH/jA++BDTe1dwGDmoduPz4+X8ZTRR+7DLbTPMLEksHTvLIC1Io4gYC3FPqlgevAbTwP/3pH7oh/PMP4VYAeQhF6e3pkRSwJe0KZe6i94cLLPZA2ln3KiR0GO72EPykD98Bm+AT4A4Lmx8VAnz2bhPYFk3smtgb9p8SBAnh9bcIVCNTCancVeUgCfsG1PCo/Xofih4r9RLgFvwICmfvyekWEmAoFwrX6wT2Wgkp+I/ev/bGIsIbZve49nINYAP24N7hPAt+ID4FPvWYDgEV/u7Y1wD1cBWpC/n2kgbsHzkJUd1k43gItQqs9Bb8hx0AHrT0pd45+c4LRfOb68oQSydAC0nqRvIXCB37o+FX9qoilR3e9hr02QlMA13kjeK9Cikibgj38j0KdhQl78jYYfWyFQgPYvkSAx4cWQrC3ZXgugnlDW/2fP1sGrEbFPae3Un1pA0J+Trr9A8BKIkJk+my8LAE1P3e5ib13iA3IV729+5iCYsCVeVu5uUJfyGnDJXyJwMtFBvypdaH9pIY7A4T/H0CxhVNCkrhR90uCJ4UpPeg+3sbKRik9ObfJPIDDGoAoO3qCrgp4wqb5H7wsARX/Knso/c+HNQiOfqA6I0FDgeH5Fzn8g1bH0IN8PUk/SgP4feB13/yrx3jETD5HgS7EmcFh+WH3jYDFRmQ/pH2hRmLGg3wkt+W9LwIswPA9HoGoSUSEAXiJuqPCGn9VexO/X8a0R6h/jTn6fwoCkbqmuMtEEcjfQnn9h39wAdu+Rneju6LHAUaVfci/9oUuAGz47rjLQFcF78G5PY3EbocwfFt2az2fgvGASX6IghCHvcQAObX4oMGDwVt6wj9pB7UGiD9YOoL95IGlfLZ5EMLfSgXCyHxG/7OBYX19uPr8JAXQx6b/Hn3CxI8BevfXORzBdMUMQkQ/OgK9hcu93fXkfFWEf0DxfjpC1IbOgzI6QPi/v8RCtzxz/hZH5QdZvgm6nz3uwH19YjrogfSJkYR++1O+DgIOvTv4yj2XBbCHDEC4/UFCnkH6+J44BAIWRjEB+H+LgplETX4StsQ7RgRjQsy+PIJ1hyrCHboSeTN/IcJUfmx+W8aCyAV+Qrlw/fLAYv1sfDVCA8jMxNy8MzxzgVS+HrjLvcWGXgbJQMV93gEjgSB59vgYgWZHA4K+PwNCjEODPbm3RrtoA6eD7f8LwbZGmsJJua94x/9+ggT/fP8axeuHXj7JuOE84wDbfd98qMKpiGDEp/xjO8zASb6U+eL9psZSR3sAmX2jgHpAUTpUeOqBKEcJA7s/J8GeAw29bzeZO2DDo4R9f/eBe4WfQgX5x/iOPx/Ch4A3/67FRccAvsd4x7xDwLi+kX1qgpxIM8SrfHX7PH+hvr36bf4yBhlHbcEFPXN/RMAoeta5K4E+R0XDzX+ewSbCOL0zuAS7ZYN5hR5AjQEJxWjBlPmQ+Pb+pAKSwRQAa8SXRpW/L/gx+98ArL7zfhADKwdHBKm89TpJ/sn/WDs2vi2GqUcPwQp9kj6i/yb7qbnQwKRH1kSQPxZA9wGIfL34n/vMgtpFokH/wHeEPIHGeXv4S791AnkBa4F0hB+FX7+buHK6ikE9f60+KoOiR1KDhb1Zuq99Zn9jfLz93QZESAFArX0vfqa+I7uZO3iAXMcYhfm/Lz9GAcK8gnhNvMKDBQU6QvaAyQKuAYQ6Wbe+vwGDvMEjAfOElMQd/zJ5bPnrABfBaT66gvdH8cMrPH77MnzCPot+Pr7eRRKIXUFaO/I+bT59uuH8B4Goxh7Fx0C6fgLAh32s+Cj8acQXBMBC80H3ga4APLsnuDA96sROAmgBOUT9Q9a94PnTuq0+y4HyQHrCNIcPxBw7oHqdPZ/98b4SwIGE28c5Qkl7/ry0Pvh7eLu/QmhGYUT9gTW+bf6PPZc5sfufRA2GLAIXwcGCIv7nusM5vL1vA7sD0QFEg9NESX2U+SN7aX7rQRIB4YLlRZDEJzxgOUo9qP6g/cOBekVEhivCC3zhO4O+G/z3u9rCPwcehKoAg/8xvcz8hPr1fFcDNwaDQxOA3gHKfuq6GXoAvmpC2ARfAofC2oNxPjd4hnsuv4lBCAIWg8aFJ4LbvQA5mTxWf2q+kwEhReXF2AFSPQT74jz4PRm9e4GuBseFbQAdPrU96/v9us99s4LdhjeDyUDpQJD+wfpDOhN+0cMbxA0DW4LQwgK+MjlReqZ/g0HgghLEKcTaQhw80Hovu+p+yn//QXFFWsXegT/8jXvTfJd9Ab5KwkGGewUSgLV9x72su/h7HT43wxuF9wPywTU/xf4sOqV6Wn7Fw01EesNEwvDBdj1CucI7DD9LQg2C1AQ8RFdBhzzZ+ji71b7hgAbCVEVwBQMBDHzIe4u8Xn1lPtFCsMYMhM4Agf4mvPL7grvCfuGDPsWqxAUBHL+QvYZ6h/sDf0zDK8Rtw8KCk8CgvXE53Tsh/4TCGwM/REjEPQCW/MO6lzuy/s3A9QJmBWFE2cBpvPp7kPvnvXQ/xYLgBbKEz8Bqvax84PtsO/e/kENKxTTESIFrvo59X3rOOxh/z8N8Q/PECILP/4781/rfuy7/eYKfAywEZoQyv848UDtyO5G+acGpgyfEhgT6wA08WLw4e/O87EC8A7uErIR2AMS9Nnxou9w71QAfBDNEWsPBwgI+X7wf+6+7uT9pg8yEHIOdgw2/aXuc+3Z8NL6Xgt7ECkP6g4uABruwe2U8mf39AXwEWUR/Q3NAsLw4+2q8kf0+AHnEvYSHQwUBUj2Bu1c8K/zR//IET4TdAvDB1b7U+wp7Rj1uf00DaETNQ2XCYz+huyg6wb2MPx7B+ATRBFMCdT/eu9m6xr16PlzA9oTmRSBCBUAA/XO6zXxpfjNAaIScBW4CJUB9/lx7EDse/hyAo0OlhRmCwEEj/zE7LfpWPi5AlsJzBLFENQFK/yJ7hnqMfeSAIcF8BFiFQgHNPp58rPsMvM0/WgE8hHCFpEHdfq39lLvn+34+XoGmxC2FDEJyf26+X7v5Oki+JUItQ2YEHkNuQKi+Zjununr904HBAo9DlsSLAfk9q/uJu159psCSQdAD4MVkgh79bfwv/Hm8hT85AeXEfgU/Ae197H0IfOC7mv3RgrpEqAQhQiu/aD32vBa6wz3LQvZEIEMRQsJBVv3Ae0w7Kr4fQgFDAAM+g8HCXX1Butn8Er5rQF5CE4PoRNhCFz07+3z86j2ZPoFCD4U/xKYBSH3mfMl9PTwIvctCgEWRA87BB/+BPgd8JjsZvgNDFQSkQueBwMFqPjT6qbsEfx5CfQLPAtMDjcIffWD6WjwdP3AAusGoQ9eE58G2PJ67fH0O/mo+9EG6RS8E3gCDfVR9Ib18vHr9xoLaRYmD2YBzvt/+fvwS+y4+VcOrBK2CdUF5QPH+F3rJewH/m4MfgsOCVkNPAjs8/XowfFD//sEhAbPDUoTQQZg8HrslfdQ+7v7gAeLFOkSkQFc8uDzM/io8zr3UQwRGNgMTv/T+v/4rvKZ7Yr5KRCLFCAHqgKmBKH4eOob7j7/4Q3FDMQGpgr7CP/zZ+bF890C6wSvBmENGREIBufvSepX+an/VfseBpMWXRHW/jLy8fJe+RP3X/f2CocaZQxm+rL6g/oF8prvR/ubDxsWvQYG/sADk/vU6OntjwMhDiAMxwaWB2QHAfZE5Zny8we1BnED3w2zEMUCSfBU6q/4jwPU/cMCbRZ2E1v6MvBt9VP5q/gs+mkJzxlXDpL22/Y4/k7zBO61/sgQPBRIB7P7JQAE/ifrJetnBm8S8ghCBdIHbAQQ9o/nOPHDCbIL7wA7ChUT/wD07PbsrPk2BHoBDAK+EkMVEPq26mz3Uv2X9+X7RgsbFx4OifZJ8qv+ivjO7AD+bhXKEhwE9/vG/RT98u5q6/MESBdsCZP/BggDBSLzQOmA8zIJrg5UAiQF/BGXAxLp/uuT/qEE1AHXAw4QARPC++3n3vTlAqv5ZfmaDW0XZApT9jjxl/w2/PjvO/v9FtsVO/93+Rf/s/vs76vuVATcF4EMtfuuA7gH3fIP5yP3OwtLDsADKgMADusE1+l36KoBYQkmAIsDgxAKELH6hejL8rkE6/4o+JkLExpeCHjy4PGl/Aj9fPO++y8VJRhx/tHzi/8B/iXvavDKBmcX+QwQ+yv/BQf69bDlJ/fiD7YOMAKUAqwLYQM/6x3oQgFBDqoBMgBgENMP5PcG6KHzggUVAvv5AAmIGYMJl+7N7xr/bP7D9ET94BRTF4L+nfDG/PwA7vDI794IDBnDC3H5/vxdBVT3cOdq9hES3hEJAPf/2QqFAsDq3uhWAksQOQSB/m0NGhAO98LlWvQGCCMEwPppCPEX8wia7dvsCgDgAez1Sf1fFUAXnvx77lD7uwHN86LwyQjuGuQLjPZj+j0FM/gd6Nf3OBOcEwgAnfzWCO0C5+pV6B8EVBPyBIb9jgtoDgX38eSs84wKaAf2+qMG4hfrB2frFuxGAFsEnPg6/WkUzhe/+9HqV/rXAwb1EfLeCewaQwzl9Of2YgTC+rLovPc5FrgUs/72+m8GKQJc7KHoLwTVFgkHnPruCUcOMPXM5H70pQt6Crr8JAQrFgwJ7+i66bQCZQbx+bj+bBOAFgL8a+hI95sGL/gw8VcLehx/CprzCPU4Aon8o+u19jYXWxiH/Ir3RwYEATjsvuqQBOwXUgoZ+VoFBg9h9fXhJ/ZNDkwLcf6TA6kS8AiF6frlWQNjCxL6WP60FIgUPPoq6Mb0nQYp/dnxRglZH1IKWu869NMBGfyv7k740hXQGq39A/KgBDIDx+pV66MHPhhJC/z5KgF7DC34gOBQ9AQTVg0k/RIE7RAmBnrqX+UvAdQPx/1O+8sUwxXA9qvmS/XbBcv/lPUuB6UePw3C6y3w+gO//N7uVfsrFvkZf/+L75n/egXm7AvpKwp6GxwKpPkMAMwIqvjV4vPxghTQErH7egGqERAEoeiy5swAtBCsAuT69xCLF0D2MeLh9ecHPgA9+DAIBhzvDR3s4eqRAwABje69+/QYTRlL/jfvDfwmBADxCOnSCMgfIwtA9i7/oAf29pfk+fKkE48W8/30/GYQRgUR5gDmBAOgEaUE5fz3DbIVKPht3zPzhQt5AjP4nQmVGxYMO+z66KUAagSx8QP6RRpRGyD8Ke0W+70Cm/Lh688HwCCQDrbzffsUCLn2J+Sy9M4UjhdKADz7Www/BnbmkuNgBNAUmgU4/UUNRBPc95ffgPCKDAIHd/iZCEMcPwtK6t7nof86BWz1e/rZGDcdA/yX6YL5XgNo817t9AjEIPMPufNa95kGgPgW5Lb00RZsGYEAOPrCCdkEzufs4rID9RcLCE78xQt7EuH2wN4D8L0MBgrO+vwGXxutC+HoduVf/x4HS/fB+2QY8xyN/GXnnfb1A671Mu40CRwikBCh8iP1YgRZ+bjllfR+F8gbXQHC964HegSq5zDjAAR1Ga4Ka/xACRYRQvfH3afucQ5uDCf8zAbKGRoLmeiz4/f9dQk6+nn7LBh6HbL7yuXO9HgD5/dG8MwIMSJ+ElLx1PHLA8/5muap9QAYxxzOAjb2BQSFBPnoD+KMBN0b2QuS/MAHvA4S94XeA+2fDoIQBP05BYEZOwpd5yPjJP0dCtv9Y/zYFTYeQvyq4mTzSgTS+DbywgkpIRoTKvL07bIBbPwt54j10RmXHaMC7fUwAYcCcOue4toCvR5bDsn6jAbADaL1FN+Q7ZgNKxNhAIECoxeAC8rlYOEa/uIKhv/R/jUUOhwu/jHhm+8pBj77PfLzCosh4RF/8tLs7v0W/qLqCPQnGnEgugET9HYAoADj61jl5wGJHpASF/quAgMOj/XQ3anugQ5mE2EDdQJeE/0LHOc63v79+w0tAJD/rRTUGaH9W+JW7B0F6v/j8oUJBSOyEX/wduxe/Ab9c+409bYXpCJWA1zw4P4mAT/rsOaKA3gdDRRF/Hv+mgvx9xDdhu3KEJYUkANzA80QaAlZ6bLdNfsPER8DIv5yFI8Zr/tb4kLs7wJ+Aqr2NAciIqkTv+4G6rj87Pyj7wj4mRaEIQAGu+6p+k0Czew05tIEjh6QE0r9ZP12BwT5dN+b60AR1BeIA0QCMhBJBybpZ9+s+R8RjQcf/p0R4xl3+6TgTew6A+4C8/mYBxAfjBSW78HmwfsN/4zwDPlpFz8gKAZh7yT3/AAm8NfmEAQcIG0USPyY/H0F5Pce4izszg9EGosF9v92DiIHoujP32H64xC3CUAAvQ4ZGLX87d/M6j4EqgQb+3UIax0cE8Dwk+VK+eEAPPMR+SQXbiCVBbvu5fUo/xDyhukvA+QfEhbh+zr6TwTo9yXjne19D5katQcH/0oLrQaf6cbfV/odEvwKKQGXDWUV0fzA4JPpAwQYB9z8wwc9HEASb/BM5fP3NQE79in61BXfHxMGqO0E9On+RfOZ66QD+R6JFl38Ovj9AZX4/eT97aoPVxtXCJn+1gglBb3q6eDo+XoSSA1uAacLyhNV/D3hmem+A3UIL/+IB70ZqBHt8CLkOPc0Aif4h/sWFWIe6wXg7ejx5v3N9VDtewPIHoMWB/we9xsARfiD513vhg4kHK8JBP2+BkwEM+sz4qb6LRKFDg4DMAkyERH9reEd6XsExglrAP4HuRd/D//xUuRK9Z8D/frZ+14Ulx3oBKjtgvFI/Gf3xvDNAmEdeBd4+yL1SP9A+NbovfE0DuoafwuE/CMD6AO/7KLibPsTE4UO7gOPCIkN3fwY5FToNgRfDFIBJgfAFosNXfHp5Wr0AQO5/hD94BH3HNoERew78XL8mve/8y8EiBpCF7v8hPKX/dj5E+rY8loPuRkUC6H9OAB7AZHvKeSp+lsUiQ//Av4HqQvQ+m7m6umBAhwOBQRMBa0ULw1p8DjmuvVeAkwALwCZDyAa9wXF62bvfP0d+cL0+wVSGaYU+P0i8k36IPs67erybA8vGrsJNf2+/6H+m/Dx5/75nhO7EYwCgwXGCuj5qOaP7HECXw3wBiMFrRCADEDxd+Vn9toDmADoAZ4PMBZXBW3th+3s/B/8JvbCBToZrRK7/A/zdvgj+i3xqPTRDWYa2Aky+7D+//008ATr1PukEWcS2wOQAmgIqfo6547tFgQADWoHZwZ0DaEJ9/Is5qH1egVqAuABaA8mFOACtu4J7kn7Of5G+QUFthckEln7bvKl+F75NfP/95YMlBiXCjT6NfzS/Uzxbezu/UgRFBHrBFwB4gS++nvpKu60BCEOTwcoBhwMgwYw84/oWvWqBdsElwKaDYkSggFh7krvKPu3/m/8oQURFeQQS/tZ8R74Tfqm9FH6Dw00FgEKb/op+oj8L/Ot7sD+jBFnEEkE4AB2AqD5+Osh8KMEsA5ICDsFFArbBMPyduqz9o0FVgYcBBQMwg+3ALzuju/1+8r/S/7NBhYTiQ4i+2LxQvfe+kL3BPwADd8UiAgj+jz5QPtb9KnxCgC5EBQQ6wNS/8AA8viZ7Z/yTwV0DsgIFgWLB6sCVPPg6+L3TwYtB/kELwsPDf/+o++J8PH7VQFpAAUHfBFpDDX6lfFQ9wn7VPnC/ngM6hLFB2j5JfjM+nv1D/T8AUYQkQ7xA3D+Q/7I+LrvevQ9BpoOiQigBBQGBwBX847uz/inBqwIfQWuCegKV/2r70Dyo/yqAfkC2wexDj8KcvlB8aD1yvgE/OUGGxYGEuz5w+x/6CT0uwgrBt0J0xhkCWDyQvGu9xX2cPYKBIEOZRZDCiv1HPmk+M7r5/DWCRIW6A3KBmz+W/no9WzpQfSTDXkPewfnCNIKlPmw7Avtufb4Cg0LvgUKDz8MW/Zi6nv0bPxV/tUG0AuUEjcM1PHV7Vf4vflW96IE7xTGDywGxfjZ8pj4ePK780sKRRdGDZEASQAB+mXwZ/BA9ZQKuxOFCFgGGAcj+4Hpfe4b/osGdAxQCggLUwt894voMvF+/lEBDAXoEXoQHAbT9jvsC/YZ+2j60wSqFbYTEQE3+NL0kPIB9V34GQgAF+YOegHh/GD7J+8F7ZX89AkIE5UM0ASFA875u+s57Mv+IArdCZ8NBg0ABYf3l+mX8Jn+xwQhByUPEhTtAhz0Ou9/8mT6+v3IBxQU7RJCAlr0EPVc9OLxwPykCiAV/g/IAXD7dfZ/8YTtHPyqDpIQuwymBgEBGvcC7K/utv2WC+sNBAu4DQUEO/P5667wY/6SBO0K4A8BEAcFEPHw7dz0dPnM/64KXhSJELgB5PW18CT0wfRT+4QOvhRYDsABAvtM9YDuMfJV/KANEBRbC9oFfABm9HHrOvATAOAJyw6CDgUJIQSY8uXpr/Kn/icGsArYErUNvgA09BTsPPMM/Pf/zwtLFWYPCf8J9b/yne+K92r/rgvOFmQN0AB2+QH1S+0a8QoCXAz2EeQOSQPr/QL1Zurh8BoBQAx+DEAQzgrK/HH0oOpi8UAAXQeHC48RaQ9G/VbxPfCS8Pn6eQUDC74UFA9K/uvyzfLU8djysgQCDigSpw8UAAj3wfMY7+3wQQLNEN0OLw3MB5T4+PJt7VXwIQJsDXgOaQzTDEz8Be7b77jx2/1wCk0NHBD3Dfb9Nu6G76b1JfddBtIQFhCdDn/+/fGE8H7zH/W3ATwU1xBpCuADnvVI8MLwLfP7AVwR9hEUCe8GUPy164rvofQCADsO6Q/qDKYIqP4o7Dbshvip/AEISRIRD34K4v3v7oPtCfbl++sBORRwEzcHBQCv8sPun/Ki+KQCAxJiFeAGLAB0+q7snO5n+HIChBAVErYKSwLD/DfuTOl4+mgCpgruEfINQgZ4+9nu5Oqf97UCFwUSEWMUfgWI+5/wr+3f9I391QWpDxQXrgZ2+df2ye5B8I76+wUFEZATQwlh/IP4i/EL6r759gfDDZQR6wq/AkL47e/k6vH26AgUCloOGBFHBef3pe5y7QL3hAKrCXcNSRSiCL/04fEb8Hb0RP0dCH4RjhJJCV/3F/O88yfvNPkgCpkRPRG9B+P9q/XY8HPu4/W/C1kQFA1uC5sCbPcG7SDugPgYB2YOFwxZDkUIsfS17Orv6vhzAlQJ5BAMEIgIvfXk7An00vWB/OwIZRP+EQ8FDfkK8ibyp/Pf91EKLxWtDvEF6Pwv95zu9e5S+gYJgROQDKYH2gPu9hfsvu0f/DMITQyGDioM5QUE96zpI/G1+zoD5Qg5EF0SyQPE9fLtAvLS+RP9YQhJFBkSNgMG9jj0g/Ja8iv8Qwl0FcUPZAJo/Mv2rPBb7RT80QxuEJwNfAZAAff3yOvl7Wj97QpTDE4LWw7LA4r0G+zf70D+kgQMCf8OnxHhBBnxPO+b9Kb4jP/jCE8T3BHVAaD0sPL39dPyq/rYDZUTdQ76AUv69PYE8arv0PohD3sS7Ai0BmYBlPUa7fHujv69C5UN4wnVCq4GrfGG6vTzMv7JBVIJxA5TD18EnfHO68z3xfv2/OYK0hNsD90A5PN/8ov1//a2+boM2ReKCsL/EvtS9vzwRfEA/cUNUBTqCEMBQQNq9iLqvfF+AP8L/gyHClYITgQc9SnnufRjA08Eugh/DzcOiQEO8qbs9vVFAH3+AwfmFosOAv3685/zufVj97X9RQqSFy0NF/pp+jf56u+N8fP/sw4IEvgJ4/+z/nX6+emG73AF5wwWC6MJ+QgWAZn0leq28UAGZAi7BDUPdQ/A/iDw1u409z7/CwPsBR0TJRK5+cPwTfZs99X2Gf8NDcwTOg3o+t30lPs/8zvv0gFyEYkQ3gbhANP8+PdO7wHuGwX9EesIjQY2CR4BhPE47A31DATeC+oFjQnREN/+i+x577r61/8EAn8J5w+KD5X8TuwB9vb7D/c3/gYPWhSrCDP7GvXj9/r36PBE/8MU6BB2A7r+sP449uruK/P3AgwT2wu6AWwHoQKO8LnqS/itBmsJfwhaCPULxAEf65DtDf63AgYBkQgiEkoLOPuI7q7yqv78+kr8+g6pFRwHMfeS9sD4F/YS9uf+KhPNE9wAavui/mL4iu1T9DMHfRBnDCICYwJ2A/3xmuk9+RUKaQoiBQoKwgmg/k/u4OvR/oAGhAGaBosRIwwi91LudvUd/Y/+Df48DG4WXgbM9En0tPta9/b0NQOQEWwStQHM95L9Gvo279Hz7ghdE+AIlwEHAtj/bvRE6lf5NgwhDCUETQZQC4f8k+w7723+cgilA/ME0A9wCxn3ceu39uAAK/2QACEM2hOtBsTyQ/OL+wH7tfUXAskUKxCR/8T3S/sS+xzx8/QmCUYUEQra/J4BggBQ8iLtEvpwDS0N0ANOBE8Iev4k64/ungK0CC8ENgWTDVcKBPbi63P1ewPaAOb9rg0fEwMELfIx8oL88/vZ+PcBZRNsEmD8/fS7/Ir6vPKM9mIKIBSGCdL8wPzYAfPzdusm/eYOiA3iAkEDgQax/Jbt2O3kAqAN9QLbA5ENTgj09Errgfc5A/MD0f+nCZsUDQPw7mny5P1o/bv5KgRZEmcQ0P378Ef7e/5T8tj3FAzsFIoHjPtf/Cr+Q/cU7aL7nRJ8DnUAuAELBlH76ewR8a4Chw4WB9H/+gsTCbnyf+oI+SAGSwNqAmMJSxDXBHDtXO/aANj/zvnNBKwTLw6C+3PygPe3//32CfZcDZ4WWwYj+FD8If5O9VrxZvw5EUgSEP+U/VUGcPvG68nxjQacDdAH1gFYBjoJ7fP958X5ogmhBMYAKwt0DjkBte+k7Yj/HQV3+oQDmBRWDvP3/PCk+RX9hPo9+W8KXhjpBo708vkNAEn14fDAAPwQ0hDSAY75TgPw/XXrS/EECfYQRAU+AlUGGATw9cDo3PfIDPYHU/+LCaEPgv4h7aPwTP4kBpr/VAFuE0kPd/Zb7av6vf/g+Eb9cwtTFaIIJfPc9dsA/feB8GkBxxQrD///9vqY/u79me5c8NgJFBQeBkz+7AYlA4zyzetj+EYMEQzY/2IGCQ/3/knqye9MAjwFkgEJBKoPIQ+I9tbq9/gXA8j6Dfy/DqkUqAUn9Frz0f5E+yDyCwEdFpARgfwh+YP/h/rn8KfyLgkEFvQHUvxhA1wEk/EV6gr8Bg1PDKUC+wN6DBr//unZ7aoDhgkaAG4F/A+IC7v2Bepk9zUEbP5Y/H0NyhbPAwLxRfQg/fz7c/U4ARkWQBK+/Kz0A/8N/DTvf/WsCsoVEQmU+2cAqgJA853pmvsYEYkM8gGVBE4JLf4N6tntbgM1DAIDuwKJEPYKx/MZ6h/3pgS7AFb+0Qx6FecEWO6N8VD/v/sd9wkD4BUrEgv8r/N8+2H9I/Fn9CoNDRdCCAn7jP4JAfjyQ+uz+2cReBCMAL0CQQkZ/Orp5+3SBAsNKQWMAycNVAtP82vn+vcbBhoCm/8tDZ8UIAPj7uHuU/6D/yn39wPUFv0Rk/r+8fD6x/uj8032+AtzGeAIY/hK/TIA7vJa6+f9BhKwEB0DVf9UB+H8r+jL7SQGZQ8yBSAErgwICBD0JOex9dcIUwS9//4MshTXAX7s3++Y/IgAL/vNAusW+RJg+VXvXPq4/CLz8/hqDcUXEAtI94T5WwCd83XrM/4KFY4QbAJgADUDRvx/6mzssQZJEnQGbQKZDFwHA/Gr6LH1wQeZCJEATwt3FBYCMeo37gH/t/8X/cIFZBQoEyn6auyB+Hv+jvRI+A8QYBi1CPr44PaU/Qj2UezA/WsWWxNNABH/tQPJ+Ivrku4jBWIUKwntACwK4Qcd8A/mffj/B40IcASUCTIStQKV6Wbrrv/9Ag38WwfPFbwPsvox7Bf1Tf9394j4Tw8hG6YH/PU0+NP6l/XY73r9ERaWFdUAR/s9A6f57ujT8AMH9BL5C00B2AbOBmDxm+RP9xMMXAhyBMwL7Q5sAcTqyOl2/gwGWv5mBTcXEBAO9zDtSPSA/aX6a/orDhYbtAkK8+D1yvzL8w/xhQDJFBYWZAIw+QoA8/rc6dTuGwozFJYKUAPkBAIEJfKE5cz1EA1NDNICOQvjDyX+verF6vX8TgeBAWoF2BSGETb2yekT9i390vqi/Q0OwBlDCkjzRPJx/JH22O8XAsgWYhQOA9T4Qf0b+iDsJu8ACcQXlwpoAaYFqgE58RTnDfa4DJgO1wRBCFsPz/7455vr8v0ZB8sDjQZiE+QPkPcM6PXzHwAf+0X+2g+NGGoJU/MY8Uj6NPhw8qkATBiGFfIAw/jl++z4HO0M8d8IoRdmDZT/RANBAufvTedz9wcNWw8pBvMHNQwS/63oVumf/4oIPASRB6USeg6V9r/oT/Lw/7L+M/6OD0gZHwiC8mLwwflK+KH0OAKGFgIXFgEN9o37mvi37RbyGwqxF2kNuQB5AJcAkPHV5t/3iA40EHYGTgdEC+b8sunz6ST+KwuxBQMHAhK4Dcf10ecG86f/xv8bAS0OSBjYCAjxM++N+ZP5S/WJAycXDxUuAgn11vhi+QPvs/JtCt0YNA2Q/2cAPP5R8VrpKfcMD/YRpwbBBQEK3vw+6Grr4/6MCnIILgfED/UM4fXj5lLyjAFpALIBww/CFQ0I1vE87fH4KPtA9/EC2xc0Fd7/n/WL98z3efEn9NEJOxlXDgb+Wf7Y/gnwL+q2+b4N5RL+BywEjwcb/fToD+r+AIQL3AcDCUcOSwqY9j7nIvEtAlADVgEtD54WIwXY8fztKvc8/Pf5WgMYFksWXv/48o74ZfdM8WH32wnkF08PIv6V++H9RPIy6Qz7zw83EQcJNQTCBAr88+ox6g0AhA5GCHAHOQ8WCAj1Quna8J0BewVwA8UM/hXpBeTu0e4C+Fr7VPwfBU4U8BSvAC3xVfbQ+YPxlfeKDFIWTA79/g36bfun87PrbfmPEW0SsQaoBKgDqPkr7EzsOf+2DiEL5wXJDBgJ5/Ic6SHz7gAyBqcFcAyiEoEGRe8g7Pj5nvwA/EEH/xNcEp8Av/EK9I/5L/Ur934MCBjQC3j+JvqX+V7zq+5/+r8PmhSMBqEBDgTZ+GHryu4YAOsNOwwkB5IJlwfO9GDnJ/QBA6EFuAb3DHYQYATr8LjrYvjG/wr9YAYRFbQQ2/5k8sfzevgI9zz6gwoEGLYMrvv2+Zn5zfI78NL8Ig9tE0oI6f87AVX6bOse72gCww3/C5kHvwhrBEP1bumW8tIEXwfpBRENbA9TAp/wRO3V9+b/bgD0BTYTMxEG/ajxYvSN+Lf3ZPyPC0cVHg28+z33C/q68+Hwbv7KD1USoAdIANn+AflA7k7v2QJTD2wLHAfCBygD5PNM6xL0uwOQCcgGKwuPDlIB8e/l7fL4MgBRAfMHBRE9D8j9OPBF9Ir5+Ph3/TYMkhSnCij8nvYg+I/1xvLY/kwQ/RGiBh3/a/6z99zucfJTAnoPWAwABj4G8AEC9Ijr9vW7BPsIWAiCCq0L4AAk8CrutvnBAUkC+gdREXcMyPxh8VTzLPr3+gT/4AsCFPUJd/oG9/33JPW09UEAYg+3EUYG8/3g/HL4SO/m87QESw5XDFIGTAQrAGL0Au1P9jMG7glxB+cKCApr/jjxGe/r+ZoCRQTJB6YPNwyc+m/xyPSt+Uv8JgG1C/gRZwkR+kX11/gv9hL25wIaD80PFAZy/R37yvfR8X70gAWfD4wK3QXtA+P9AvRC75v30QVYC8sHjAjCCfL8EvBh8bL6qQKSBf8ITg1RCjT70O9h9Yr7IfzMAtUMyg9lB3H6ufRS9474ovfLAq4QDg4gBJ/9P/p+9lvzivfFBMoPSAtJAy0Dkf2P8tzwF/rJBcwKSAlFB5AGo/2T75XxW/3KAoYFFgqEDOAG2fo98SD0Jf10/iYCrg0lD3AE0fnA9aP2gPhO+xADZA/bDtUBQPzs+s31lvN/+joGvg2oC2UD9v+N/R7zp/C2/BoHyQkLCeMHsAOU+/XxefEg/kwFBQXNCYgMngSx+OfyXvUe/CsByQO/CzAP8ALN95/2nvc0+O/8EAZtDUcNfALH+Vn6IPe08x/8egj+DIEJAQTb/qD6APUH8gv9VwmYCaAHigfcAs/4cfKH9If9Vwb4BiYIkwuuA6P27fKY96n85wCjBkALKgz5Am72zPUn+Rz5ff3iBwEOAQqpAVf6BPjh9+H1lvznCUYNlQd7Aib/+fjh83/19v0rCd4KZgbxBSICtfem8dL2xf8+BSUI1gieCJ8CCPZn8gf5bv5BAfAGtQybCVUAVfcM9WH5KfuB/ooIWg6lCPf+h/pg+Fz2Nfjl/r4Jjw2WBscAL/4Q+UTzovZuAdEINQoIBx0EiQBG983x8/f6AUcGDgetCcUHaP8e9gbzr/n6/4YCPQdeDCkJg/1Y9s72Gvkh/MsAEQnfDWgHff0d+Q35A/cj+O4B0woRDOwFp//w/GX4D/Sh9ycDvAq7CBwGJwRG/kX2rvJ9+T8DSAdbB0oIiAes/QH0pvQS+6sApAMYCMMLZgdp/Nf0K/cb+xj8KQLHCuAMjAUb/Lf4Z/gQ+JT5nALfDFQLnQMN/zn8bvdD9Lz5kQQwCyMJJAQNA/v9YfQh86z7yARVB5IHFwhJBdP8/fJI9JH91AGvA9wI1AteBT768fQE9/X7Pv41AssLMQ0vAzX6nPjG+Kz3g/ttBL8MuwviAeT8V/wp9+rzXvscBzsLMQgqBOAA8/yN9IHylv0hB5IHqQZICEQEIvoy8+X0Of5PBCoEWQgyDDQEqPdC9M/4Fvxb/3QENwsuDUACpfcJ+AT6IPjI+zEHhQ36CZMBP/vk+jT4I/QR/I4JjAxnBiYDAAF7+mD03PME/lIJ1ghtBUcHTAQq+GrxCfd3/7UEMAbSBw4L5QO49ajyMPox/un+/gXBDBYLUgGG9lf27Pq9+fX7OgiqD4cIBv9/+4X5hfcO9qT8xQo2DpwFkgDQAE76IPJt9TsAkQkzCkMFQgWeA7v3ne9y97kCCgUWBmEJVwlPAin1O/Fq+p8ADABTBXoO2AoN/hD2APZM+pr7Uf1dCMEQwwgE/Nv5pPo29oj2Qv8oC9cOpwWA/vD+z/qK8Y70WQMmC00J0wUiBIEBbfci7xL3zwSFB/EESgkMCmz/7vN28Uz6GAIPAlMF/g28CwL8OfMa9676pfuN/yQJmhDMCKD6S/fQ+qT3hPUeAZANIA4/BZb9Cf0x+l7yZPRBBDkODQkeBIYE7P/X9ZHvfPfmBYoJsgWIBzQKBP/38LHxtPu2ApIDXQZiDRgLg/vZ8Cv2Bv3y+wIASQtxENYHkvnT9c752vii9tUA7g8CDyIDu/w4/BH5ofJ29Q0Fqg9+ClMC9AJRAAj0Au/1+C4HsgphBgYHgAjd/tLvA/Cc/XMEyAM6B38N/Qk4+uHvK/XQ/VD+1f/vC7wRVwbd99f0hPkQ+QX45gE5EHYQKwIo+vj72fgx8mH2lAbDELwKDALhAGr/YfSu7c35WwmyC1oGnAa7B0v9X++G77X9AAfFBKwG4A1pCZ74b+5Q9WX+ev+CAYALJxJWBoD1e/PC+cv5dfgyA1gRKRD4AW74IvqV+WPygvYZCFASsgq1ADwA4v3380julvkfC4ANBAaABTQHjPzN7a/vvv7XB6IGjwbRDHAJcffL7AH1IABQABwCsgxdEd8FnfR+8cj5Pfs4+YMDtxKoEDwAjfcV+cr4xvPq9rAI6RM9Cw7/s/4A/tjyTe4B+7EL8w6TBucDEgZm/PTssO5uAIcJsgZzB/0LJQg094/rPvR0AWAC7wHfDC8SJwRr8/Pw7Ph6/ND6nAP6EqIRMf8A9Sv5s/iU86n4NAloFAUMDv5y/KH9ifNG7fL71A35Dt0GYwMdBO/7Eu0C7sEAMAxFB10GkgzlBsT1jOu78/8BdgTdAssLkhJBBM3wYPCp+XT8cvypBI8SyBEp/8ryn/dX+qLzxvhFC48UvgvP/az6Rfxv9M3tV/vaD44QXgUNA2UDWfpX7WLuyACpDT8JEAVPC5AHBfSC6sf0awKbBVkERQtVEZME0+8V7vD66/1T/B0G6RLtENv+5vHO9cj6vPVC+NsLehapCqj8J/r5+n/0Mu+c+xEQshIdBZsAkQPQ+VHsZO+eAU8OkwpGBTEJJQd99JLoBvV+BAEGCQWkCycQugPM78jsQPp/AAb9fwUgFHIQbv1H8Q31cPpd95r5EQuBF3ELO/ov+Rr7AfQD8NL8WxAuE+8Fsv63AeT6vusA714DPg/aCnAFKAiABbz0oujd81sG+gdlBLQL4w97Ah7vquzy+Y4BYP/4BIgTXBEF/LbvFfWz+hv4//qKC+wWHwx2+aD2e/vW9O/v2/1cEUwTowUO/sD/e/oU7Wzu5wNIEeoKnQRlB38E9PP86BH0dAYuCt8EDwrCD/cB7O1N7JP6XwKDANgFUBL7ED780u1v9PL7Bfmk+yIMAhdjCyb5VPVM+oL2w/DO/W0S6BPvBM78C//V+aDtlO+4A24SKAxYAyAGFAS287bouPR/B9sK/QUbCS4OJAJe7YDrNfv4A1kB5wVCEtwPt/t87RzzzfzV+hP8EAwyFywLqveZ9Ov5yfaR8iP+XBK+FJYEIfvu/T366u0g8OoEnRLZDCIDIgRgAxn02Oiw9OAIJwy1BdwI+gwiAb7tIutB+5QFyQJ+BWMR0g+U+rvsTfPa/H/8S/2WC7oWNwvK9tXyTPrG9x7zYP9fEnEUsQTT+Vj8bPpJ70TwZgUGFG4MhgIkA+EBXfSs6db0TAnaDdMFHwd8DHUABu3E64P7ZQZOBIsF1g8hD8D6QOsl80X+G/1j/rwLohWtCob2fvGT+a35KfQr/0QTHBSvA0X5DPsV+rDwe/EBBdEUXw2wAA0CiwHY84zqxfWMCakOtQaRBZQK9QCn7ETr9vwxB/4E/QWqDpkNy/o/693xrf8e/yz+6AtGFWYJA/Yd8db4pvp59g//mxILFXwCs/fi+tb5hvEO83EFUhQ2Di4AZ/9/AZL0b+r79ogKwg4HBwAFdwhUAADuu+pJ/XYJOgWgBSsONAz/+cbr1PGd/6ABIf9zCk8V6AiN9AHxHfks+zL4RQBrEa8UBAOE9fr5AfsX8hf0gAYfFKwNPgC3/dT/LvZV68b2FwxlD1AGVwQzBxf/rO7968j82goGBz4EDQ25CwL5ouuk8gcAmQLuAHgJcBNKCavzt+8G+j38Hfk5ATgRNBPYAhn15/fY+xH0VfQTB5QU5AxT//z8ff5f9pLt//YJDPwQtgWuAmIGhf607i3ttf3dCo0IRgSUCiALFvkB6yXzWAF9A6EBkQmUESwIPvSM7ub5Xf4z+msBGBFqEpMByPQ791T7VPbE9X0G8BTVDNv9yvsn/o321+6e+LgLOBFlBqsAxASd/hnvv+3e/r0LrgiOBAQJDgmV+Vvr4/KuAv0E6gHtCJsQtAbd8wbvVvnB/1r8TwFKEOQRvgCW8w/3uftd98z3lwbpE/8M8fwF+rL9gPf074/5jwzAEEQG7f+FAlT+VfBx7m3/4gw1CawD7gedB+n4iuxP8yIDywafAt8HLQ8jBi/zAe82+mwAK/4iAvMO3hBgAMTyRvan/P/4x/hXB0AT/wux/KT4yfyV+MHxRPrBDD4RVgXR/mIBX/1y8fXv4/9tDQsKFQPpBaUGuPiy7JD0zAOmB6cD+wY4DSAFaPOY7qz6LAIb/7MCSQ4jD6b/gPKm9ez8D/s0+usGFRMeC237DPgM/DD5sPOQ+3AMJBFnBff8BgBw/fLxcPEDAY8NWAr2AiEEwgRA+XLt2vRYBYkI3QOLBnkLpAOL8z7vifqVAxkBWgJmDSkORv4s8r/1Lv2B/Df8yQaiEQYLSvqU9jD83vkf9Rb9kwwyECcFKfzL/Wr9jfMs8iYCUw4DCmwC7gLtAtf4Mu9o9bIFWArrA0oFSgpTAhzzKfBL+w4E/wIUA1YLHA3N/RLx9/Ug/p79rv13BxQQtgli+gb1dfuc+3r2+v0pDYcPBASU+4b8RPxk9f3zFgI5D0IKHwGoAdABPPhK8D/3xwUTCzEFnQNUCNoBs/KC8KD8AAXBAxYEJgqpCsz96vA09Xr/U/+P/tAHXg/dB735AvVG+q78HPlw/hMNeg/PAkb66PvE+xH2i/bJAp8OGAtFAHv//QBQ+Orw0PgDB/MKxwVUA5MF6wB685vwif2kBpIEIASgCZ8IY/zO8QH1rP/AAcP/WQeuDrUGWPjT9HL6xPxv+ygA+QsDD2kCm/jU+g==```

**Comment by npezza93** [comment]
@mofux Oh I like that one!

**Comment by mofux** [comment]
@npezza93 Your short bell version is also very good!

Time to spread some emojis guys! Choose the reaction of the sound you like most, if `none of them` wins we'll open up another round:
👍 https://github.com/sourcelair/xterm.js/files/1232998/bell.zip
❤️ https://freesound.org/people/jonnay/sounds/3168/
🎉 https://freesound.org/people/altemark/sounds/45759/
👎 None of them

**Comment by parisk** [comment]
I voted ❤️, as it's a little bit more discreet.

**Comment by parisk** [comment]
Should we go with "🎉 https://freesound.org/people/altemark/sounds/45759/" then 😄?

**Comment by Tyriar** [comment]
It's nice and small too, might not be worth bothering with lazy loading if it's that small

File: src/xterm.css [hunk 14]
```diff
@@ -124,6 +126,14 @@
     height: 1px;
 }
 
+.terminal.focus.xterm-cursor-style-block.visual-bell-active .terminal-cursor {
+  background-color: #ccc !important;
```
Comment (Tyriar) [inline src/xterm.css]: Might be better to transition on opacity so that consumers that use custom themes don't need to deal with the visual bell?

File: src/Terminal.ts [hunk 15]
```diff
@@ -2271,6 +2282,27 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
...
+  }
+
+  private preloadBellSound(): void {
+    if (this.soundBell()) {
+      this.bellAudioElement = document.createElement('audio');
+      this.bellAudioElement.setAttribute('preload', 'auto');
+      this.bellAudioElement.setAttribute('src', this.options.bellSound);
+      this.element.appendChild(this.bellAudioElement);
+    } else if (this.bellAudioElement) {
+      this.bellAudioElement.remove();
```
Comment (Tyriar) [inline src/Terminal.ts]: Support for `ChildNode.remove` isn't very good, we should use `Node.removeChild` instead to improve compatibility.

**Comment by npezza93** [comment]
Should be good now @Tyriar!

File: src/xterm.css [hunk 16]
```diff
@@ -124,6 +126,14 @@
     height: 1px;
 }
 
+.terminal.focus.xterm-cursor-style-block.visual-bell-active .terminal-cursor {
+  opacity: 0.5;
+}
+.terminal.focus.xterm-cursor-style-bar.visual-bell-active .terminal-cursor::before,
+.terminal.focus.xterm-cursor-style-underline.visual-bell-active .terminal-cursor::before {
+  background-color: transparent;
```
Comment (Tyriar) [inline src/xterm.css]: I think this needs to be opacity: 0

File: src/xterm.css [hunk 17]
```diff
@@ -91,6 +91,7 @@
 
 .terminal .terminal-cursor {
     position: relative;
+    transition: background-color 150ms ease;
```
Comment (Tyriar) [inline src/xterm.css]: transition: opacity...?

File: src/xterm.css [hunk 18]
```diff
@@ -108,6 +109,7 @@
     content: '';
     position: absolute;
     background-color: #fff;
+    transition: background-color 150ms ease;
```
Comment (Tyriar) [inline src/xterm.css]: transition: opacity...?

File: src/Terminal.ts [hunk 19]
```diff
@@ -2271,6 +2282,27 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
...
+  }
+
+  private preloadBellSound(): void {
+    if (this.soundBell()) {
+      this.bellAudioElement = document.createElement('audio');
+      this.bellAudioElement.setAttribute('preload', 'auto');
+      this.bellAudioElement.setAttribute('src', this.options.bellSound);
+      this.element.appendChild(this.bellAudioElement);
+    } else if (this.bellAudioElement) {
+      this.element.removeChild(this.bellAudioElement);
```
Comment (Tyriar) [inline src/Terminal.ts]: Now that I'm reading this again, it should be added/removed to `this.helperContainer` instead of `this.element`.

**Comment by Tyriar** [comment]
Woo! Let's merge 😄

**Comment by Tyriar** [comment]
Thanks for the contribution @npezza93 🎆
