### PR TITLE
fix(ime): resync textarea position when composition starts

### LINKED ISSUE #5734: IME composition window positioned incorrectly when terminal displays placeholder text
## Description

  When using Chinese IME (Input Method Editor) in xterm.js, the composition candidate window appears
  at an incorrect position when the terminal application displays placeholder/hint text (e.g., Claude
  Code CLI's "Try 'fix lint errors'" prompt). The IME window appears at the end of the placeholder
  text instead of at the actual cursor position (beginning of the line).

Image

  This issue does not occur in native terminal emulators like Windows Terminal with the same shell and
   application, suggesting it's specific to xterm.js's IME handling.

  ## Details
  - Browser and browser version: Electron 33.2.1 (Chromium 130.0.6723.120)
  - OS version: Windows 11 Pro 10.0.22621
  - xterm.js version: 6.0.0

  ## Steps to reproduce

  1. Create an Electron app with xterm.js 6.0.0
  2. Connect xterm.js to a PTY running PowerShell 7
  3. Launch Claude Code CLI (or any CLI app that displays placeholder/hint text using ANSI escape
  sequences)
  4. When the placeholder text appears (e.g., "Try 'fix lint errors'"), activate Chinese IME
  5. Start typing with IME (e.g., type "nihao" to get Chinese characters)

  ## Expected behavior

  The IME composition candidate window should appear at the actual cursor position (beginning of the
  line where input will be inserted), just like it does in Windows Terminal.

  ## Actual behavior

  The IME composition candidate window appears at the end of the placeholder text, not at the actual
  cursor position. After typing a space (which causes the placeholder to disappear), subsequent IME
  input shows the candidate window at the correct position.

  ## Additional context

  - The issue only affects the **first** IME composition when placeholder text is visible
  - After the placeholder disappears (e.g., after typing space), IME positioning works correctly
  - The same setup works correctly in Windows Terminal, indicating this is xterm.js-specific
  - The placeholder text is likely rendered using ANSI escape sequences by the terminal application
  - The `.xterm-helper-textarea` element seems to have incorrect cursor position information when
  placeholder text is present

## Workarounds attempted

  - Setting `selectionStart` and `selectionEnd` to 0 in compositionstart event → breaks input
  functionality
  - Clearing textarea value → causes input loss
  - Sending dummy characters to hide placeholder → causes input duplication

  None of these workarounds resolved the issue without breaking normal input functionality.

  ## Related issues

  This may be related to:
  - #3533 (Sogou Chinese IME support)
  - #3679 (CJK IME input broken on Windows in Electron 13)

  However, those issues describe different symptoms (input not working at all), while this issue is
  specifically about IME candidate window positioning.

### PR DESCRIPTION
**Pull request by SergioChan**
## Summary
- sync the helper textarea position right before `compositionstart` is processed
- trigger an immediate composition element update after composition starts so IME anchoring uses the latest cursor position
- this avoids stale IME anchor coordinates when prompt UIs briefly draw helper text and restore the cursor before the first composition render tick

## Testing
- `npm run lint -- src/browser/CoreBrowserTerminal.ts` *(fails in this environment because project dev dependencies are not installed yet, so `eslint` is unavailable)*

## Related
- Fixes #5734

### CODE REVIEW

File: src/browser/CoreBrowserTerminal.ts [hunk 1]
```diff
@@ -414,7 +414,14 @@ export class CoreBrowserTerminal extends CoreTerminal implements ITerminal {
     this._register(addDisposableListener(this.textarea!, 'keyup', (ev: KeyboardEvent) => this._keyUp(ev), true));
     this._register(addDisposableListener(this.textarea!, 'keydown', (ev: KeyboardEvent) => this._keyDown(ev), true));
     this._register(addDisposableListener(this.textarea!, 'keypress', (ev: KeyboardEvent) => this._keyPress(ev), true));
-    this._register(addDisposableListener(this.textarea!, 'compositionstart', () => this._compositionHelper!.compositionstart()));
+    this._register(addDisposableListener(this.textarea!, 'compositionstart', () => {
+      // Ensure the textarea is synced to the latest cursor location before composition begins.
+      // Some prompt UIs briefly draw helper text and then restore the cursor without triggering a
+      // new key event, which can leave IME anchoring stale until the first render tick.
+      this._syncTextArea();
+      this._compositionHelper!.compositionstart();
```
Comment (Tyriar) [inline src/browser/CoreBrowserTerminal.ts:424]: Fix seems reasonable. I reproduced a problem similar to the video once but could not seem to do it again. The sync is meant to happen immediately after cursor move:

https://github.com/xtermjs/xterm.js/blob/89980fc565c178d13588e135f8eb975f44a47712/src/browser/CoreBrowserTerminal.ts#L337-L340

This happens after a full parse has occurred (not for every write):

https://github.com/xtermjs/xterm.js/blob/89980fc565c178d13588e135f8eb975f44a47712/src/common/InputHandler.ts#L519-L521

So the only thing I can think of that could cause it is a race condition where the data events are coming in separate chunks such that the cursor position is not in the final position (likely still hidden as the rendering is still occurring), triggering composition during one of these partial re-renders would cause `isComposing` to be true and the position of the element to become locked until composition has ended and the cursor moves again.

File: src/browser/CoreBrowserTerminal.ts [hunk 2]
```diff
@@ -414,7 +414,14 @@ export class CoreBrowserTerminal extends CoreTerminal implements ITerminal {
     this._register(addDisposableListener(this.textarea!, 'keyup', (ev: KeyboardEvent) => this._keyUp(ev), true));
     this._register(addDisposableListener(this.textarea!, 'keydown', (ev: KeyboardEvent) => this._keyDown(ev), true));
     this._register(addDisposableListener(this.textarea!, 'keypress', (ev: KeyboardEvent) => this._keyPress(ev), true));
-    this._register(addDisposableListener(this.textarea!, 'compositionstart', () => this._compositionHelper!.compositionstart()));
+    this._register(addDisposableListener(this.textarea!, 'compositionstart', () => {
+      // Ensure the textarea is synced to the latest cursor location before composition begins.
+      // Some prompt UIs briefly draw helper text and then restore the cursor without triggering a
+      // new key event, which can leave IME anchoring stale until the first render tick.
```
Comment (Tyriar) [inline src/browser/CoreBrowserTerminal.ts]:
```suggestion
      // Ensure the textarea is synced to the latest cursor location before composition begins. This
      // is to workaround a problem where highly dynamic TUIs like agentic CLIs reprint agressively
      // would cause the IME to appear in the wrong position. The theory is that when the IME is
      // triggered during a partial render the textarea position becomes locked and will not move
      // until it is hidden and a custom move occurs.
```

File: src/browser/CoreBrowserTerminal.ts (hunk 1 above)
Comment (Tyriar) [reply src/browser/CoreBrowserTerminal.ts:424]: Note that I was testing on mac, reprinting probably happens in more chunks on Windows so this theory makes sense in that respect.
