### PR TITLE
Fix entering hash (#) on British keyboard layout

### LINKED ISSUE #169: Cannot enter # on Mac UK keyboard
I had to patch term.js previously to get # working on a Mac UK keyboard (shift + 3).

https://github.com/BenHall/term.js/commit/edf03f4656bd7eb5df1151dcfb1ba1a1d19287b0

I tried to do the same patch xterm but it didn't work. I added the following code at line 2568

https://github.com/sourcelair/xterm.js/blob/39edbfb6558343dc556b094470a84448d6a7a4d2/src/xterm.js#L2568

```
        case 51:
          result.key = "#";
          break;
```

Please help, it's stopping our migration.

Thank you

Ben

### PR DESCRIPTION
**Pull request by parisk**
This PR closes #169.

### CODE REVIEW

File: src/xterm.js [hunk 1]
```diff
@@ -4953,8 +4953,8 @@
           (term.isMac && ev.altKey && !ev.ctrlKey && !ev.metaKey) ||
           (term.isMSWindows && ev.altKey && ev.ctrlKey && !ev.metaKey);
 
-      // Don't invoke for arrows, pageDown, home, backspace, etc.
-      return thirdLevelKey && (!ev.keyCode || ev.keyCode > 47);
+      // Don't invoke for arrows, pageDown, home, backspace, etc. (on non-keypress events)
+      return thirdLevelKey && ((ev.type != 'keypress') ? (!ev.keyCode || ev.keyCode > 47) : true);
```
Comment (Tyriar) [inline src/xterm.js]: Can you change this to an early exit at the start of the function to reduce complexity? ie.

```js
function isThirdLevelShift(term, ev) {
  if (ev.type === 'keypress') {
    return true;
  }
  ...
}
```

Comment (parisk) [inline src/xterm.js]: Thanks @Tyriar. Updated code: https://github.com/sourcelair/xterm.js/pull/178/commits/42ec3b492a24b110007a73f5f8ff48a4e4d83737.
